# Generated by Django 5.0.3 on 2024-08-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_profiles", "0003_profile_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="biography",
            field=models.TextField(blank=True, null=True, verbose_name="biography"),
        ),
    ]
