# Generated by Django 4.2 on 2025-03-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="profileevent",
            name="name",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True, verbose_name="name"
            ),
        ),
    ]
