# Generated by Django 5.1.15 on 2026-02-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_message_templates", "0003_alter_emailtemplate_name_alter_smstemplate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="html_content",
            field=models.TextField(
                blank=True,
                help_text="Text that will be inputted into Template html version",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="plain_text_content",
            field=models.TextField(
                blank=True, help_text="Text that will be inputted into Template plain text version"
            ),
        ),
    ]
