# Generated by Django 5.2.3 on 2025-10-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_message_templates", "0003_alter_emailtemplate_name_alter_smstemplate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="html_content",
            field=models.TextField(
                blank=True, help_text="HTML content for the template", null=True
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="plain_text_content",
            field=models.TextField(
                blank=True,
                help_text="Plain text (will be sanitized HTML; render as text/plain when sending)",
            ),
        ),
    ]
