# Generated by Django 5.1.11 on 2025-07-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_notifications", "0002_notificationsetting"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="baseapp_not_recipie_8567c3_idx",
            old_fields=("recipient", "unread"),
        ),
    ]
