# Generated by Django 4.2.15 on 2024-08-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_comments", "0012_alter_comment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentevent",
            name="id",
            field=models.BigIntegerField(),
        ),
    ]
