# Generated by Django 5.0.9 on 2024-10-09 14:18

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_comments", "0015_alter_commentevent_pgh_context_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentevent",
            name="in_reply_to",
        ),
        migrations.RemoveField(
            model_name="commentevent",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="commentevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="commentevent",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="commentevent",
            name="target_content_type",
        ),
        migrations.RemoveField(
            model_name="commentevent",
            name="user",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="delete_delete",
        ),
        migrations.DeleteModel(
            name="CommentEvent",
        ),
    ]
