# Generated by Django 5.1.13 on 2025-10-23 01:48

import baseapp.files.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_comments", "0017_alter_comment_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="files_count",
            field=models.JSONField(default=baseapp.files.utils.default_files_count),
        ),
    ]
