# Generated by Django 5.1.13 on 2025-10-23 19:39

from django.db import migrations, models

import baseapp.files.utils


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_comments", "0017_alter_comment_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="files_count",
            field=models.JSONField(default=baseapp.files.utils.default_files_count),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_files_enabled",
            field=models.BooleanField(default=True, verbose_name="is files enabled"),
        ),
    ]
