# Generated by Django 5.1.11 on 2025-09-11 18:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_comments", "0017_alter_comment_profile"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_comments' AND model = 'comment')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="1559ce2d31e6ab537a999e4e416c17931480e317",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_08ece",
                    table="baseapp_comments_comment",
                    when="AFTER",
                ),
            ),
        ),
    ]
