# Generated by Django 5.1.15 on 2025-12-24 14:22

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_comments", "0017_alter_comment_profile"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_comments' AND model = 'comment'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="36bf2dc1fd37828497dd3cc06ab84f6a98e1b05f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_a9dd9",
                    table="baseapp_comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_comments' AND model = 'comment')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="ad6878dfd687bcd8a1d4e95652193655f2c345f1",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_285c9",
                    table="baseapp_comments_comment",
                    when="AFTER",
                ),
            ),
        ),
    ]
