# Generated by Django 5.2.12 on 2026-04-27 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_comments", "0018_comment_insert_document_id_and_more"),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="mentioned_profiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_mentions",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                verbose_name="mentioned profiles",
            ),
        ),
    ]
