# Generated by Django 5.1.11 on 2025-11-17 15:01

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import baseapp_comments.models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_comments", "0018_comment_insert_public_id_mapping_and_more"),
        ("baseapp_core", "0002_documentid"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentStats",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "target",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="comment_stats",
                        serialize=False,
                        to="baseapp_core.documentid",
                    ),
                ),
                (
                    "comments_count",
                    models.JSONField(
                        default=baseapp_comments.models.default_comments_count, editable=False
                    ),
                ),
                ("is_comments_enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "baseapp_comments_commentstats",
            },
        ),
    ]
