# Generated by Django 5.0.10 on 2025-01-14 20:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0008_alter_chatroomparticipant_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
