# Generated by Django 5.0.11 on 2025-03-07 18:31

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0010_message_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroomparticipant",
            options={"ordering": ["-role"]},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="message",
            name="create_message_status",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="messagestatus",
            name="increment_unread_count",
        ),
    ]
