# Generated by Django 5.1.14 on 2025-12-03 04:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_reports", "0006_delete_old_rename_new_report_type"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_reports' AND model = 'report'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="42a7b63a4f460fc6d8d66fdb128ac621cd1daaf7",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_76c62",
                    table="baseapp_reports_report",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_reports' AND model = 'report')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="7650fef0e33ce8ba6055a5a83a757021bcd944dc",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_7bb91",
                    table="baseapp_reports_report",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reporttype",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_reports' AND model = 'reporttype'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="ecc1c010da8db30166c8a2a4030fb02481716c7c",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_c586a",
                    table="baseapp_reports_reporttype",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reporttype",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_reports' AND model = 'reporttype')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="2481e05f4ce57a713d319152ef3543dba2955a68",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_f60bd",
                    table="baseapp_reports_reporttype",
                    when="AFTER",
                ),
            ),
        ),
    ]
