# Generated by Django 5.1.15 on 2025-12-24 14:28

import django.db.models.deletion
import django.utils.timezone
import django_quill.fields
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import baseapp_comments.models
import baseapp_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pghistory", "0006_delete_aggregateevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "comments_count",
                    models.JSONField(
                        default=baseapp_comments.models.default_comments_count,
                        editable=False,
                        verbose_name="comments count",
                    ),
                ),
                (
                    "is_comments_enabled",
                    models.BooleanField(default=True, verbose_name="is comments enabled"),
                ),
                (
                    "title_en",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_es",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_pt",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "body_en",
                    django_quill.fields.QuillField(blank=True, null=True, verbose_name="body"),
                ),
                (
                    "body_es",
                    django_quill.fields.QuillField(blank=True, null=True, verbose_name="body"),
                ),
                (
                    "body_pt",
                    django_quill.fields.QuillField(blank=True, null=True, verbose_name="body"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Draft"), (2, "Published")], db_index=True, default=2
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "db_table": "baseapp_pages_page",
                "abstract": False,
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PageEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "comments_count",
                    models.JSONField(
                        default=baseapp_comments.models.default_comments_count,
                        editable=False,
                        verbose_name="comments count",
                    ),
                ),
                (
                    "is_comments_enabled",
                    models.BooleanField(default=True, verbose_name="is comments enabled"),
                ),
                (
                    "title_en",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_es",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_pt",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "body_en",
                    django_quill.fields.QuillField(blank=True, null=True, verbose_name="body"),
                ),
                (
                    "body_es",
                    django_quill.fields.QuillField(blank=True, null=True, verbose_name="body"),
                ),
                (
                    "body_pt",
                    django_quill.fields.QuillField(blank=True, null=True, verbose_name="body"),
                ),
                (
                    "status",
                    models.IntegerField(choices=[(1, "Draft"), (2, "Published")], default=2),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to=settings.BASEAPP_PAGES_PAGE_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "comments_count", "created", "id", "is_comments_enabled", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (NEW."body_en", NEW."body_es", NEW."body_pt", NEW."comments_count", NEW."created", NEW."id", NEW."is_comments_enabled", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."title_en", NEW."title_es", NEW."title_pt", NEW."user_id"); RETURN NULL;',
                    hash="4f00021f0384715ca1aab12c5095d609d5e3f006",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_e8067",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "comments_count", "created", "id", "is_comments_enabled", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (NEW."body_en", NEW."body_es", NEW."body_pt", NEW."comments_count", NEW."created", NEW."id", NEW."is_comments_enabled", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."title_en", NEW."title_es", NEW."title_pt", NEW."user_id"); RETURN NULL;',
                    hash="f299c5b136480bc75096b1099d6ae4c8ec61f4de",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_847b7",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "comments_count", "created", "id", "is_comments_enabled", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (OLD."body_en", OLD."body_es", OLD."body_pt", OLD."comments_count", OLD."created", OLD."id", OLD."is_comments_enabled", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."title_en", OLD."title_es", OLD."title_pt", OLD."user_id"); RETURN NULL;',
                    hash="75ca8bbaf141656f076363b9f28addb253c2788a",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_f1297",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'pages' AND model = 'page'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="dba12f14fed3885d47ca87a70b95f503fbe145b8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_2f334",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'pages' AND model = 'page')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="58bd88faaff6b1d1ef82dff256ee4a4f87a60212",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_188c9",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
    ]
