# Generated by Django 5.1.15 on 2026-02-10 14:13

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="delete_delete",
        ),
        migrations.RemoveField(
            model_name="page",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="page",
            name="is_comments_enabled",
        ),
        migrations.RemoveField(
            model_name="pageevent",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="pageevent",
            name="is_comments_enabled",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (NEW."body_en", NEW."body_es", NEW."body_pt", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."title_en", NEW."title_es", NEW."title_pt", NEW."user_id"); RETURN NULL;',
                    hash="5ef56324128183d7564e2b609eba62639d94cd35",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_e8067",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (NEW."body_en", NEW."body_es", NEW."body_pt", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."title_en", NEW."title_es", NEW."title_pt", NEW."user_id"); RETURN NULL;',
                    hash="ff8f0128576808b306ea1533f6c7bdc2d72b08e4",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_847b7",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (OLD."body_en", OLD."body_es", OLD."body_pt", OLD."created", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."title_en", OLD."title_es", OLD."title_pt", OLD."user_id"); RETURN NULL;',
                    hash="a24c7ce3c2a4c469d51600c63c180264cb86ea8d",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_f1297",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
    ]
