# Generated by Django 5.2.12 on 2026-03-23 17:45

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="delete_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="delete_document_id",
        ),
        migrations.AlterModelTable(
            name="page",
            table=None,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "comments_count", "created", "id", "is_comments_enabled", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (NEW."body_en", NEW."body_es", NEW."body_pt", NEW."comments_count", NEW."created", NEW."id", NEW."is_comments_enabled", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."title_en", NEW."title_es", NEW."title_pt", NEW."user_id"); RETURN NULL;',
                    hash="9c8bac758de88e7260bdf875a80fe302b7a5ee6d",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_e8067",
                    table="pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "comments_count", "created", "id", "is_comments_enabled", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (NEW."body_en", NEW."body_es", NEW."body_pt", NEW."comments_count", NEW."created", NEW."id", NEW."is_comments_enabled", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."title_en", NEW."title_es", NEW."title_pt", NEW."user_id"); RETURN NULL;',
                    hash="2ef5af6241db3612f03a523ebf816f5462f0d79d",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_847b7",
                    table="pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "comments_count", "created", "id", "is_comments_enabled", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (OLD."body_en", OLD."body_es", OLD."body_pt", OLD."comments_count", OLD."created", OLD."id", OLD."is_comments_enabled", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."title_en", OLD."title_es", OLD."title_pt", OLD."user_id"); RETURN NULL;',
                    hash="022a0fa72e4ddd70383af2b1abc90913be30afdc",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_f1297",
                    table="pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'pages' AND model = 'page'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="ec6bd78720f03e692db0fc5659521a3eca542107",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_2f334",
                    table="pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'pages' AND model = 'page')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="823876c9190d78afecf5c936a19ea27e50794433",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_188c9",
                    table="pages_page",
                    when="AFTER",
                ),
            ),
        ),
    ]
