# Generated by Django 5.2.12 on 2026-04-22 19:14

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_remove_page_insert_insert_remove_page_update_update_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="delete_delete",
        ),
        migrations.RemoveField(
            model_name="page",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="page",
            name="is_comments_enabled",
        ),
        migrations.RemoveField(
            model_name="pageevent",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="pageevent",
            name="is_comments_enabled",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (NEW."body_en", NEW."body_es", NEW."body_pt", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."title_en", NEW."title_es", NEW."title_pt", NEW."user_id"); RETURN NULL;',
                    hash="e4da3b6147c61a0e76a435116c80b0a600cf6eca",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_e8067",
                    table="pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (NEW."body_en", NEW."body_es", NEW."body_pt", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."title_en", NEW."title_es", NEW."title_pt", NEW."user_id"); RETURN NULL;',
                    hash="c49cf5be8621159ba5edf06a3b04603b760ae0da",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_847b7",
                    table="pages_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pages_pageevent" ("body_en", "body_es", "body_pt", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "title_en", "title_es", "title_pt", "user_id") VALUES (OLD."body_en", OLD."body_es", OLD."body_pt", OLD."created", OLD."id", OLD."modified", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."title_en", OLD."title_es", OLD."title_pt", OLD."user_id"); RETURN NULL;',
                    hash="721d162e50848c6257846057d8e2309c598569fc",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_f1297",
                    table="pages_page",
                    when="AFTER",
                ),
            ),
        ),
    ]
