# Generated by Django 5.0.8 on 2025-03-25 21:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_delete_standardpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagefortests",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("custom_image_chooser_block", 0),
                    ("custom_image_block", 3),
                    ("custom_rich_text_block", 4),
                    ("banner_block", 10),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "baseapp_wagtail.base.blocks.basic_blocks.custom_image_chooser_block.block.CustomImageChooserBlock",
                        (),
                        {},
                    ),
                    1: (
                        "baseapp_wagtail.base.blocks.basic_blocks.custom_image_chooser_block.block.CustomImageChooserBlock",
                        (),
                        {"image_sizes": None, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'If this is a <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">decorative image</a>, please leave this field blank.',
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("image", 1), ("alt_text", 2)]], {}),
                    4: ("wagtail.blocks.RichTextBlock", (), {}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True, "use_json_field": True},
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ul", "hr"],
                            "icon": "pilcrow",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {"admin_text": "<hr />", "label": " "},
                    ),
                    8: (
                        "baseapp_wagtail.base.blocks.basic_blocks.custom_image_chooser_block.block.CustomImageChooserBlock",
                        (),
                        {"label": " ", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [("left", "Left"), ("right", "Right")],
                            "help_text": "This indicates the position of the image in the desktop view.",
                            "label": "Image Position",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("description", 6),
                                ("hr", 7),
                                ("featured_image", 8),
                                ("image_position", 9),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
    ]
