# Generated by Django 5.1.15 on 2026-01-15 01:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import baseapp.files.utils
import baseapp_comments.models
import baseapp_core.models
import baseapp_reactions.models
import baseapp_reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseapp_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileTarget",
            fields=[
                (
                    "target",
                    models.OneToOneField(
                        help_text="The document this file target belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="file_target",
                        serialize=False,
                        to="baseapp_core.documentid",
                    ),
                ),
                ("files_count", models.JSONField(default=baseapp.files.utils.default_files_count)),
                (
                    "is_files_enabled",
                    models.BooleanField(default=True, verbose_name="is files enabled"),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BASEAPP_FILES_FILETARGET_MODEL",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "reports_count",
                    models.JSONField(default=baseapp_reports.models.default_reports_count),
                ),
                (
                    "reactions_count",
                    models.JSONField(
                        default=baseapp_reactions.models.default_reactions_count, editable=False
                    ),
                ),
                ("is_reactions_enabled", models.BooleanField(default=True)),
                (
                    "comments_count",
                    models.JSONField(
                        default=baseapp_comments.models.default_comments_count,
                        editable=False,
                        verbose_name="comments count",
                    ),
                ),
                (
                    "is_comments_enabled",
                    models.BooleanField(default=True, verbose_name="is comments enabled"),
                ),
                ("file_content_type", models.CharField(blank=True, max_length=150, null=True)),
                ("file_name", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes", null=True),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=512, upload_to=baseapp_core.models.random_name_in("files")
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=512, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Upload"),
                            ("uploading", "Upload in Progress"),
                            ("completed", "Upload Completed"),
                            ("failed", "Upload Failed"),
                            ("aborted", "Upload Aborted"),
                        ],
                        db_index=True,
                        default="completed",
                        help_text="Status of the file upload",
                        max_length=20,
                    ),
                ),
                (
                    "upload_id",
                    models.CharField(
                        blank=True,
                        help_text="S3 multipart upload ID for in-progress uploads",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "total_parts",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total number of parts for multipart upload",
                        null=True,
                    ),
                ),
                (
                    "uploaded_parts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tracking uploaded parts with ETags",
                        null=True,
                    ),
                ),
                (
                    "upload_expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Expiration time for pending uploads",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent document this file belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="baseapp_core.documentid",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                        verbose_name="profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BASEAPP_FILES_FILE_MODEL",
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'files' AND model = 'file'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="6f43d1588d53b00ddfa0d5a563a4cd0dbb9e6f62",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_d067b",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'files' AND model = 'file')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="877efe613614ca4ef5d93a264fde512958f34df2",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_23af1",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
    ]
