# Generated by Django 5.1.13 on 2025-11-27 01:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import baseapp.files.utils
import baseapp_comments.models
import baseapp_core.models
import baseapp_reactions.models
import baseapp_reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "reports_count",
                    models.JSONField(default=baseapp_reports.models.default_reports_count),
                ),
                (
                    "reactions_count",
                    models.JSONField(
                        default=baseapp_reactions.models.default_reactions_count, editable=False
                    ),
                ),
                ("is_reactions_enabled", models.BooleanField(default=True)),
                (
                    "comments_count",
                    models.JSONField(
                        default=baseapp_comments.models.default_comments_count,
                        editable=False,
                        verbose_name="comments count",
                    ),
                ),
                (
                    "is_comments_enabled",
                    models.BooleanField(default=True, verbose_name="is comments enabled"),
                ),
                ("parent_object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("file_content_type", models.CharField(blank=True, max_length=150, null=True)),
                ("file_name", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes", null=True),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=512, upload_to=baseapp_core.models.random_name_in("files")
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=512, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                        verbose_name="profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BASEAPP_FILES_FILE_MODEL",
            },
        ),
        migrations.CreateModel(
            name="FileTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_object_id", models.PositiveIntegerField(db_index=True)),
                ("files_count", models.JSONField(default=baseapp.files.utils.default_files_count)),
                (
                    "is_files_enabled",
                    models.BooleanField(default=True, verbose_name="is files enabled"),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BASEAPP_FILES_FILETARGET_MODEL",
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    DECLARE\n                        new_counts JSONB;\n                    BEGIN\n                        IF NEW.parent_content_type_id IS NOT NULL AND NEW.parent_object_id IS NOT NULL THEN\n                            -- Calculate new counts\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO new_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_content_type_id = NEW.parent_content_type_id\n                                AND parent_object_id = NEW.parent_object_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            -- Insert or update FileTarget\n                            INSERT INTO files_filetarget (target_content_type_id, target_object_id, files_count, is_files_enabled)\n                            VALUES (NEW.parent_content_type_id, NEW.parent_object_id, new_counts, true)\n                            ON CONFLICT (target_content_type_id, target_object_id)\n                            DO UPDATE SET files_count = new_counts;\n                        END IF;\n                        RETURN NEW;\n                    END;\n                ",
                    hash="d6e51cf71c64992d24cec64fec95e1d46a764b52",
                    operation="INSERT",
                    pgid="pgtrigger_update_file_target_on_insert_8a1d9",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    DECLARE\n                        new_counts JSONB;\n                        old_counts JSONB;\n                    BEGIN\n                        -- Update old parent if it changed\n                        IF (OLD.parent_content_type_id IS DISTINCT FROM NEW.parent_content_type_id\n                            OR OLD.parent_object_id IS DISTINCT FROM NEW.parent_object_id)\n                            AND OLD.parent_content_type_id IS NOT NULL\n                            AND OLD.parent_object_id IS NOT NULL THEN\n\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO old_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_content_type_id = OLD.parent_content_type_id\n                                AND parent_object_id = OLD.parent_object_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            UPDATE files_filetarget SET files_count = old_counts\n                            WHERE target_content_type_id = OLD.parent_content_type_id\n                            AND target_object_id = OLD.parent_object_id;\n                        END IF;\n\n                        -- Update new parent\n                        IF NEW.parent_content_type_id IS NOT NULL AND NEW.parent_object_id IS NOT NULL THEN\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO new_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_content_type_id = NEW.parent_content_type_id\n                                AND parent_object_id = NEW.parent_object_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            INSERT INTO files_filetarget (target_content_type_id, target_object_id, files_count, is_files_enabled)\n                            VALUES (NEW.parent_content_type_id, NEW.parent_object_id, new_counts, true)\n                            ON CONFLICT (target_content_type_id, target_object_id)\n                            DO UPDATE SET files_count = new_counts;\n                        END IF;\n\n                        RETURN NEW;\n                    END;\n                ",
                    hash="5a7566e39e37e8c08949b9cbe19953acccdff8a7",
                    operation="UPDATE",
                    pgid="pgtrigger_update_file_target_on_update_89baa",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    DECLARE\n                        new_counts JSONB;\n                    BEGIN\n                        IF OLD.parent_content_type_id IS NOT NULL AND OLD.parent_object_id IS NOT NULL THEN\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO new_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_content_type_id = OLD.parent_content_type_id\n                                AND parent_object_id = OLD.parent_object_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            UPDATE files_filetarget SET files_count = new_counts\n                            WHERE target_content_type_id = OLD.parent_content_type_id\n                            AND target_object_id = OLD.parent_object_id;\n                        END IF;\n\n                        RETURN OLD;\n                    END;\n                ",
                    hash="49d43ee24ecd9a0a6184abb357d05ef192269649",
                    operation="DELETE",
                    pgid="pgtrigger_update_file_target_on_delete_3c3fa",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="filetarget",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="files_filet_target__08e7b2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filetarget",
            unique_together={("target_content_type", "target_object_id")},
        ),
    ]
