# Generated by Django 5.2.14 on 2026-06-26 21:23

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import baseapp.files.utils
import baseapp_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseapp_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileTarget",
            fields=[
                (
                    "target",
                    models.OneToOneField(
                        help_text="The document this file target belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="file_target",
                        serialize=False,
                        to="baseapp_core.documentid",
                    ),
                ),
                ("files_count", models.JSONField(default=baseapp.files.utils.default_files_count)),
                (
                    "is_files_enabled",
                    models.BooleanField(default=True, verbose_name="is files enabled"),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BASEAPP_FILES_FILETARGET_MODEL",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("file_content_type", models.CharField(blank=True, max_length=150, null=True)),
                ("file_name", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes", null=True),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=512, upload_to=baseapp_core.models.random_name_in("files")
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=512, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Upload"),
                            ("uploading", "Upload in Progress"),
                            ("completed", "Upload Completed"),
                            ("failed", "Upload Failed"),
                            ("aborted", "Upload Aborted"),
                        ],
                        db_index=True,
                        default="completed",
                        help_text="Status of the file upload",
                        max_length=20,
                    ),
                ),
                (
                    "upload_id",
                    models.CharField(
                        blank=True,
                        help_text="S3 multipart upload ID for in-progress uploads",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "total_parts",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total number of parts for multipart upload",
                        null=True,
                    ),
                ),
                (
                    "uploaded_parts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tracking uploaded parts with ETags",
                        null=True,
                    ),
                ),
                (
                    "upload_expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Expiration time for pending uploads",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent document this file belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="baseapp_core.documentid",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                        verbose_name="profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BASEAPP_FILES_FILE_MODEL",
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'files' AND model = 'file'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="6f43d1588d53b00ddfa0d5a563a4cd0dbb9e6f62",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_d067b",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'files' AND model = 'file')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="877efe613614ca4ef5d93a264fde512958f34df2",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_23af1",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DECLARE\n                new_counts JSONB;\n            BEGIN\n                IF NEW.parent_id IS NOT NULL THEN\n                    -- Calculate new counts\n                    SELECT COALESCE(\n                        jsonb_object_agg(\n                            file_content_type,\n                            count\n                        ) || jsonb_build_object('total', SUM(count)),\n                        '{\"total\": 0}'::jsonb\n                    ) INTO new_counts\n                    FROM (\n                        SELECT\n                            COALESCE(file_content_type, 'unknown') as file_content_type,\n                            COUNT(*)::int as count\n                        FROM files_file\n                        WHERE parent_id = NEW.parent_id\n                        GROUP BY file_content_type\n                    ) counts;\n\n                    -- Insert or update FileTarget\n                    INSERT INTO files_filetarget (target_id, files_count, is_files_enabled)\n                    VALUES (NEW.parent_id, new_counts, true)\n                    ON CONFLICT (target_id)\n                    DO UPDATE SET files_count = new_counts;\n                END IF;\n                RETURN NEW;\n            END;\n            ",
                    hash="fe7e8e6f14c341e981b6cec3920eb6ba96222706",
                    operation="INSERT",
                    pgid="pgtrigger_update_file_target_on_insert_8a1d9",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DECLARE\n                new_counts JSONB;\n                old_counts JSONB;\n            BEGIN\n                -- Update old parent if it changed\n                IF OLD.parent_id IS DISTINCT FROM NEW.parent_id\n                    AND OLD.parent_id IS NOT NULL THEN\n\n                    SELECT COALESCE(\n                        jsonb_object_agg(\n                            file_content_type,\n                            count\n                        ) || jsonb_build_object('total', SUM(count)),\n                        '{\"total\": 0}'::jsonb\n                    ) INTO old_counts\n                    FROM (\n                        SELECT\n                            COALESCE(file_content_type, 'unknown') as file_content_type,\n                            COUNT(*)::int as count\n                        FROM files_file\n                        WHERE parent_id = OLD.parent_id\n                        GROUP BY file_content_type\n                    ) counts;\n\n                    UPDATE files_filetarget SET files_count = old_counts\n                    WHERE target_id = OLD.parent_id;\n                END IF;\n\n                -- Update new parent\n                IF NEW.parent_id IS NOT NULL THEN\n                    SELECT COALESCE(\n                        jsonb_object_agg(\n                            file_content_type,\n                            count\n                        ) || jsonb_build_object('total', SUM(count)),\n                        '{\"total\": 0}'::jsonb\n                    ) INTO new_counts\n                    FROM (\n                        SELECT\n                            COALESCE(file_content_type, 'unknown') as file_content_type,\n                            COUNT(*)::int as count\n                        FROM files_file\n                        WHERE parent_id = NEW.parent_id\n                        GROUP BY file_content_type\n                    ) counts;\n\n                    INSERT INTO files_filetarget (target_id, files_count, is_files_enabled)\n                    VALUES (NEW.parent_id, new_counts, true)\n                    ON CONFLICT (target_id)\n                    DO UPDATE SET files_count = new_counts;\n                END IF;\n\n                RETURN NEW;\n            END;\n            ",
                    hash="4e27b58158d9658648a4a79af0d8bfed613196ef",
                    operation="UPDATE",
                    pgid="pgtrigger_update_file_target_on_update_89baa",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DECLARE\n                new_counts JSONB;\n            BEGIN\n                IF OLD.parent_id IS NOT NULL THEN\n                    SELECT COALESCE(\n                        jsonb_object_agg(\n                            file_content_type,\n                            count\n                        ) || jsonb_build_object('total', SUM(count)),\n                        '{\"total\": 0}'::jsonb\n                    ) INTO new_counts\n                    FROM (\n                        SELECT\n                            COALESCE(file_content_type, 'unknown') as file_content_type,\n                            COUNT(*)::int as count\n                        FROM files_file\n                        WHERE parent_id = OLD.parent_id\n                        GROUP BY file_content_type\n                    ) counts;\n\n                    UPDATE files_filetarget SET files_count = new_counts\n                    WHERE target_id = OLD.parent_id;\n                END IF;\n\n                RETURN OLD;\n            END;\n            ",
                    hash="3ccd45f3c662961c3959e628d80113b1a4203f1b",
                    operation="DELETE",
                    pgid="pgtrigger_update_file_target_on_delete_3c3fa",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
    ]
