# Generated by Django 5.1.13 on 2025-12-09 03:08

from django.db import migrations, models

import baseapp_core.models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="file",
            name="state",
            field=models.IntegerField(
                choices=[(1, 'Initial'), (2, 'Receiving'), (3, 'Saving'), (4, 'Done')],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="upload_length",
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="file",
            name="upload_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="file",
            name="upload_offset",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=baseapp_core.models.random_name_in("files"),
            ),
        ),
    ]
