# Generated by Django 5.1.13 on 2025-11-27 01:34

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    -- Get the swappable FileTarget table name\n                    DECLARE\n                        file_target_table TEXT;\n                        new_counts JSONB;\n                    BEGIN\n                        -- Get FileTarget table name from app registry\n                        SELECT pg_class.relname INTO file_target_table\n                        FROM pg_class\n                        JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace\n                        WHERE pg_namespace.nspname = 'public'\n                        AND pg_class.relname LIKE '%filetarget';\n\n                        IF NEW.parent_content_type_id IS NOT NULL AND NEW.parent_object_id IS NOT NULL THEN\n                            -- Calculate new counts\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO new_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_content_type_id = NEW.parent_content_type_id\n                                AND parent_object_id = NEW.parent_object_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            -- Insert or update FileTarget\n                            EXECUTE format(\n                                'INSERT INTO %I (target_content_type_id, target_object_id, files_count, is_files_enabled)\n                                VALUES ($1, $2, $3, true)\n                                ON CONFLICT (target_content_type_id, target_object_id)\n                                DO UPDATE SET files_count = $3',\n                                file_target_table\n                            ) USING NEW.parent_content_type_id, NEW.parent_object_id, new_counts;\n                        END IF;\n                        RETURN NEW;\n                    END;\n                ",
                    hash="5f0f6d3950223d3844e858ef0ba08a3a7dacd020",
                    operation="INSERT",
                    pgid="pgtrigger_update_file_target_on_insert_8a1d9",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    DECLARE\n                        file_target_table TEXT;\n                        new_counts JSONB;\n                        old_counts JSONB;\n                    BEGIN\n                        SELECT pg_class.relname INTO file_target_table\n                        FROM pg_class\n                        JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace\n                        WHERE pg_namespace.nspname = 'public'\n                        AND pg_class.relname LIKE '%filetarget';\n\n                        -- Update old parent if it changed\n                        IF (OLD.parent_content_type_id IS DISTINCT FROM NEW.parent_content_type_id\n                            OR OLD.parent_object_id IS DISTINCT FROM NEW.parent_object_id)\n                            AND OLD.parent_content_type_id IS NOT NULL\n                            AND OLD.parent_object_id IS NOT NULL THEN\n\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO old_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_content_type_id = OLD.parent_content_type_id\n                                AND parent_object_id = OLD.parent_object_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            EXECUTE format(\n                                'UPDATE %I SET files_count = $1\n                                WHERE target_content_type_id = $2 AND target_object_id = $3',\n                                file_target_table\n                            ) USING old_counts, OLD.parent_content_type_id, OLD.parent_object_id;\n                        END IF;\n\n                        -- Update new parent\n                        IF NEW.parent_content_type_id IS NOT NULL AND NEW.parent_object_id IS NOT NULL THEN\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO new_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_content_type_id = NEW.parent_content_type_id\n                                AND parent_object_id = NEW.parent_object_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            EXECUTE format(\n                                'INSERT INTO %I (target_content_type_id, target_object_id, files_count, is_files_enabled)\n                                VALUES ($1, $2, $3, true)\n                                ON CONFLICT (target_content_type_id, target_object_id)\n                                DO UPDATE SET files_count = $3',\n                                file_target_table\n                            ) USING NEW.parent_content_type_id, NEW.parent_object_id, new_counts;\n                        END IF;\n\n                        RETURN NEW;\n                    END;\n                ",
                    hash="54b26e933be952f0651d41c5e336029f01d50389",
                    operation="UPDATE",
                    pgid="pgtrigger_update_file_target_on_update_89baa",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    DECLARE\n                        file_target_table TEXT;\n                        new_counts JSONB;\n                    BEGIN\n                        SELECT pg_class.relname INTO file_target_table\n                        FROM pg_class\n                        JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace\n                        WHERE pg_namespace.nspname = 'public'\n                        AND pg_class.relname LIKE '%filetarget';\n\n                        IF OLD.parent_content_type_id IS NOT NULL AND OLD.parent_object_id IS NOT NULL THEN\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO new_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_content_type_id = OLD.parent_content_type_id\n                                AND parent_object_id = OLD.parent_object_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            EXECUTE format(\n                                'UPDATE %I SET files_count = $1\n                                WHERE target_content_type_id = $2 AND target_object_id = $3',\n                                file_target_table\n                            ) USING new_counts, OLD.parent_content_type_id, OLD.parent_object_id;\n                        END IF;\n\n                        RETURN OLD;\n                    END;\n                ",
                    hash="ce3eeedf4c32a426255874a92ee641c02d8a2829",
                    operation="DELETE",
                    pgid="pgtrigger_update_file_target_on_delete_3c3fa",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
    ]
