# Generated by Django 5.1.15 on 2026-01-15 02:04

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    DECLARE\n                        new_counts JSONB;\n                    BEGIN\n                        IF NEW.parent_id IS NOT NULL THEN\n                            -- Calculate new counts\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO new_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_id = NEW.parent_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            -- Insert or update FileTarget\n                            INSERT INTO files_filetarget (target_id, files_count, is_files_enabled)\n                            VALUES (NEW.parent_id, new_counts, true)\n                            ON CONFLICT (target_id)\n                            DO UPDATE SET files_count = new_counts;\n                        END IF;\n                        RETURN NEW;\n                    END;\n                ",
                    hash="2ce68c38624f0c7693cfdfb4a9014172526e7b62",
                    operation="INSERT",
                    pgid="pgtrigger_update_file_target_on_insert_8a1d9",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    DECLARE\n                        new_counts JSONB;\n                        old_counts JSONB;\n                    BEGIN\n                        -- Update old parent if it changed\n                        IF OLD.parent_id IS DISTINCT FROM NEW.parent_id\n                            AND OLD.parent_id IS NOT NULL THEN\n\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO old_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_id = OLD.parent_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            UPDATE files_filetarget SET files_count = old_counts\n                            WHERE target_id = OLD.parent_id;\n                        END IF;\n\n                        -- Update new parent\n                        IF NEW.parent_id IS NOT NULL THEN\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO new_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_id = NEW.parent_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            INSERT INTO files_filetarget (target_id, files_count, is_files_enabled)\n                            VALUES (NEW.parent_id, new_counts, true)\n                            ON CONFLICT (target_id)\n                            DO UPDATE SET files_count = new_counts;\n                        END IF;\n\n                        RETURN NEW;\n                    END;\n                ",
                    hash="24c6665cc0695aa57e26b4bbbcafdbff218cc06d",
                    operation="UPDATE",
                    pgid="pgtrigger_update_file_target_on_update_89baa",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="update_file_target_on_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    DECLARE\n                        new_counts JSONB;\n                    BEGIN\n                        IF OLD.parent_id IS NOT NULL THEN\n                            SELECT COALESCE(\n                                jsonb_object_agg(\n                                    file_content_type,\n                                    count\n                                ) || jsonb_build_object('total', SUM(count)),\n                                '{\"total\": 0}'::jsonb\n                            ) INTO new_counts\n                            FROM (\n                                SELECT\n                                    COALESCE(file_content_type, 'unknown') as file_content_type,\n                                    COUNT(*)::int as count\n                                FROM files_file\n                                WHERE parent_id = OLD.parent_id\n                                GROUP BY file_content_type\n                            ) counts;\n\n                            UPDATE files_filetarget SET files_count = new_counts\n                            WHERE target_id = OLD.parent_id;\n                        END IF;\n\n                        RETURN OLD;\n                    END;\n                ",
                    hash="227a0fc65140c3d76f13f87bbad3eb45073ad260",
                    operation="DELETE",
                    pgid="pgtrigger_update_file_target_on_delete_3c3fa",
                    table="files_file",
                    when="AFTER",
                ),
            ),
        ),
    ]
