# Generated by Django 5.1.13 on 2025-12-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="total_parts",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total number of parts for multipart upload", null=True
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="upload_expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Expiration time for pending uploads",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="upload_id",
            field=models.CharField(
                blank=True,
                help_text="S3 multipart upload ID for in-progress uploads",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Upload"),
                    ("uploading", "Upload in Progress"),
                    ("completed", "Upload Completed"),
                    ("failed", "Upload Failed"),
                    ("aborted", "Upload Aborted"),
                ],
                db_index=True,
                default="completed",
                help_text="Status of the file upload",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="uploaded_parts",
            field=models.JSONField(
                blank=True, default=dict, help_text="Tracking uploaded parts with ETags", null=True
            ),
        ),
    ]
