# Generated by Django 5.2.14 on 2026-07-12 00:54

from django.db import migrations, models

# These string fields dropped null=True in favour of default="". Convert any
# existing NULLs to "" before the AlterField enforces NOT NULL, so the
# migration is safe on databases populated by the previous schema.
NULLABLE_STRING_FIELDS = ("description", "file_content_type", "file_name", "name", "upload_id")


def fill_null_strings(apps, schema_editor):
    File = apps.get_model("files", "File")
    for field in NULLABLE_STRING_FIELDS:
        File.objects.filter(**{f"{field}__isnull": True}).update(**{field: ""})


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fill_null_strings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_content_type",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_name",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="file",
            name="upload_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="S3 multipart upload ID for in-progress uploads",
                max_length=512,
            ),
        ),
    ]
