# Generated by Django 5.2.14 on 2026-07-12 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import baseapp.files.utils
import baseapp_core.models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("files", "0002_alter_file_description_alter_file_file_content_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name": "file", "verbose_name_plural": "files"},
        ),
        migrations.AlterModelOptions(
            name="filetarget",
            options={"verbose_name": "file target", "verbose_name_plural": "file targets"},
        ),
        migrations.AlterField(
            model_name="file",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who uploaded the file",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional description of the file",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                help_text="The stored file",
                max_length=512,
                upload_to=baseapp_core.models.random_name_in("files"),
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_content_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MIME type of the uploaded file",
                max_length=150,
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Original name of the uploaded file",
                max_length=512,
                verbose_name="file name",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_size",
            field=models.PositiveIntegerField(
                help_text="File size in bytes", null=True, verbose_name="file size"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display name for the file",
                max_length=512,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent document this file belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="baseapp_core.documentid",
                verbose_name="parent",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="total_parts",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total number of parts for multipart upload",
                null=True,
                verbose_name="total parts",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="upload_expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Expiration time for pending uploads",
                null=True,
                verbose_name="upload expires at",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="upload_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="S3 multipart upload ID for in-progress uploads",
                max_length=512,
                verbose_name="upload ID",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Upload"),
                    ("uploading", "Upload in Progress"),
                    ("completed", "Upload Completed"),
                    ("failed", "Upload Failed"),
                    ("aborted", "Upload Aborted"),
                ],
                db_index=True,
                default="completed",
                help_text="Status of the file upload",
                max_length=20,
                verbose_name="upload status",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="uploaded_parts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tracking uploaded parts with ETags",
                null=True,
                verbose_name="uploaded parts",
            ),
        ),
        migrations.AlterField(
            model_name="filetarget",
            name="files_count",
            field=models.JSONField(
                default=baseapp.files.utils.default_files_count,
                help_text="Per-content-type file counts for the target",
                verbose_name="files count",
            ),
        ),
        migrations.AlterField(
            model_name="filetarget",
            name="is_files_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether files can be attached to the target",
                verbose_name="is files enabled",
            ),
        ),
        migrations.AlterField(
            model_name="filetarget",
            name="target",
            field=models.OneToOneField(
                help_text="The document this file target belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="file_target",
                serialize=False,
                to="baseapp_core.documentid",
                verbose_name="target",
            ),
        ),
    ]
