# Generated by Django 5.2.17 on 2026-10-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_file_options_alter_filetarget_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="profile",
        ),
    ]
