# Generated by Django 5.2.14 on 2026-05-19 12:10

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_mentions", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="mention",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="mention",
            name="delete_document_id",
        ),
    ]
