# Generated by Django 5.2.14 on 2026-07-18 20:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseapp_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoJSONFeature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                (
                    "feature_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="feature type",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        geography=True, srid=4326, verbose_name="geometry"
                    ),
                ),
                (
                    "target_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="baseapp_core.documentid",
                        verbose_name="target document",
                    ),
                ),
            ],
            options={
                "verbose_name": "geojson feature",
                "verbose_name_plural": "geojson features",
                "abstract": False,
                "swappable": "BASEAPP_GEO_GEOJSONFEATURE_MODEL",
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="geojsonfeature",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'geo' AND model = 'geojsonfeature'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="3a92e7f2d2b055b936e9bef19df83d737ec3e242",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_e6256",
                    table="geo_geojsonfeature",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="geojsonfeature",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'geo' AND model = 'geojsonfeature')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="8462c1ae98f1331d248b286eae5d6dba9f72dbc7",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_8872a",
                    table="geo_geojsonfeature",
                    when="AFTER",
                ),
            ),
        ),
    ]
