# Generated by Django 5.2.17 on 2026-10-09 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="geojsonfeature",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created the feature",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geo_features_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="geojsonfeature",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The profile the feature was created under",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="geo_features",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                verbose_name="profile",
            ),
        ),
    ]
