# Generated by Django 5.1.13 on 2025-11-14 02:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoJSONFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        help_text="Geographic data in any geometry type (Point, LineString, Polygon, etc.)",
                        srid=4326,
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "GeoJSON Feature",
                "verbose_name_plural": "GeoJSON Features",
                "abstract": False,
                "swappable": "BASEAPP_MAPS_GEOJSONFEATURE_MODEL",
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="baseapp_map_target__1543b6_idx",
                    )
                ],
            },
        ),
    ]
