# Generated by Django 5.1.13 on 2025-11-14 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_maps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="geojsonfeature",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this feature",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geojson_features",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
