# Generated by Django 5.1.13 on 2025-11-14 03:26

from django.db import migrations


def populate_user_field(apps, schema_editor):
    """Populate user field for existing GeoJSONFeature records."""
    GeoJSONFeature = apps.get_model("baseapp_maps", "GeoJSONFeature")
    User = apps.get_model("users", "User")

    # Get the first superuser, or create one if none exists
    superuser = User.objects.filter(is_superuser=True).first()
    if not superuser:
        # If no superuser exists, get the first user
        superuser = User.objects.first()

    if superuser:
        # Update all GeoJSONFeature records without a user
        GeoJSONFeature.objects.filter(user__isnull=True).update(user=superuser)


def reverse_populate_user_field(apps, schema_editor):
    """Reverse migration - set user field to null."""
    GeoJSONFeature = apps.get_model("baseapp_maps", "GeoJSONFeature")
    GeoJSONFeature.objects.all().update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_maps", "0002_geojsonfeature_user"),
        ("users", "0001_initial"),  # Ensure User model exists
    ]

    operations = [
        migrations.RunPython(populate_user_field, reverse_populate_user_field),
    ]
