# Generated by Django 5.1.4 on 2024-12-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_activity_log", "0002_auto_20241216_1804"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivityLog",
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("ip_address", models.TextField()),
                ("verb", models.TextField()),
                ("visibility", models.TextField()),
                ("url", models.TextField()),
                ("metadata", models.JSONField()),
            ],
            options={
                "db_table": "v_activity_log",
                "managed": False,
            },
        ),
    ]
