# Generated by Django 5.0.1 on 2024-06-21 01:52
import swapper
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_blocks", "0003_migrate_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        swapper.dependency("baseapp_profiles", "Profile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("actor", "target")},
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(fields=["target", "actor"], name="baseapp_blo_target__031766_idx"),
        ),
        migrations.RemoveField(
            model_name="block",
            name="actor_content_type",
        ),
        migrations.RemoveField(
            model_name="block",
            name="actor_object_id",
        ),
        migrations.RemoveField(
            model_name="block",
            name="target_content_type",
        ),
        migrations.RemoveField(
            model_name="block",
            name="target_object_id",
        ),
    ]
