# Generated by Django 5.1.14 on 2025-12-03 04:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_blocks", "0004_alter_block_unique_together_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="block",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_blocks' AND model = 'block'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="b9636ec2af7f33b222b3e23a7c31cd7c123b00cf",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_a4954",
                    table="baseapp_blocks_block",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="block",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_blocks' AND model = 'block')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="00f2418145cc96dc178784b5de5048bef2e45359",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_b7d8e",
                    table="baseapp_blocks_block",
                    when="AFTER",
                ),
            ),
        ),
    ]
