# Generated by Django 5.1.11 on 2025-09-11 18:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_blocks", "0004_alter_block_unique_together_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="block",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_blocks' AND model = 'block')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="ecf3cd6e89376571443dfc8d6b72685c99f88c28",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_29f03",
                    table="baseapp_blocks_block",
                    when="AFTER",
                ),
            ),
        ),
    ]
