# Generated by Django 5.2.3 on 2025-11-12 16:03

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_blocks", "0005_block_insert_public_id_mapping_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="block",
            name="insert_public_id_mapping",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="block",
            name="delete_public_id_mapping",
        ),
    ]
