# Generated by Django 5.1.15 on 2025-12-24 14:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import baseapp_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("target_is_following_back", models.BooleanField(default=False)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                        verbose_name="target",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("actor", "target")},
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="follow",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'follows' AND model = 'follow'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="2d463daac11ef602802b3fad87cdb7a3d25d6bf9",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_02212",
                    table="follows_follow",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="follow",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'follows' AND model = 'follow')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="7bf35b65a4a27bdc39710dd536983f4930794e79",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_b160d",
                    table="follows_follow",
                    when="AFTER",
                ),
            ),
        ),
    ]
