# Generated by Django 5.2.14 on 2026-06-08 13:03

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import baseapp_follows.migration_helpers.convert_follow_profile_fks_into_document_id_helper
import baseapp_follows.migration_helpers.seed_followable_metadata_from_follows_helper


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("follows", "0002_alter_follow_actor_alter_follow_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowableMetadata",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "target",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="followable_metadata",
                        serialize=False,
                        to="baseapp_core.documentid",
                    ),
                ),
                ("followers_count", models.PositiveIntegerField(default=0, editable=False)),
                ("following_count", models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                "verbose_name": "followable metadata",
                "verbose_name_plural": "followable metadata",
                "abstract": False,
                "swappable": "BASEAPP_FOLLOWS_FOLLOWABLEMETADATA_MODEL",
            },
        ),
        migrations.RunPython(
            code=baseapp_follows.migration_helpers.convert_follow_profile_fks_into_document_id_helper.migrate_follow_profile_fks_to_document_id,
            reverse_code=baseapp_follows.migration_helpers.convert_follow_profile_fks_into_document_id_helper.reverse_migrate_follow_document_id_fks_to_profile,
        ),
        migrations.RunPython(
            code=baseapp_follows.migration_helpers.seed_followable_metadata_from_follows_helper.seed_followable_metadata_from_follows,
            reverse_code=baseapp_follows.migration_helpers.seed_followable_metadata_from_follows_helper.reverse_seed_followable_metadata,
        ),
        migrations.AlterField(
            model_name="followablemetadata",
            name="target",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="baseapp_core.documentid",
            ),
        ),
    ]
