# Generated by Django 5.0.9 on 2025-01-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
