# Generated by Django 5.0.9 on 2025-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_devices", "0002_alter_userdevice_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="device_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
