# Generated by Django 5.1.7 on 2025-04-01 03:35

import django.db.models.deletion
import swapper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_content_feed", "0003_alter_contentpostimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpostimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to=swapper.get_model_name("baseapp_content_feed", "ContentPost"),
                verbose_name="post",
            ),
        ),
    ]
