# Generated by Django 5.1.8 on 2025-04-10 23:56

from django.db import migrations, models

import baseapp_reactions.models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_content_feed", "0004_alter_contentpostimage_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpost",
            name="is_reactions_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contentpost",
            name="reactions_count",
            field=models.JSONField(
                default=baseapp_reactions.models.default_reactions_count, editable=False
            ),
        ),
    ]
