# Generated by Django 5.1.14 on 2025-12-03 04:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_content_feed", "0005_contentpost_is_reactions_enabled_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="contentpost",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_content_feed' AND model = 'contentpost'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="e851a61bbd22b489686c3f86f7745b527730a292",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_11ffb",
                    table="baseapp_content_feed_contentpost",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="contentpost",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_content_feed' AND model = 'contentpost')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="17f8877f3f931b006933d3c0b82e5f8a9accd299",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_0423f",
                    table="baseapp_content_feed_contentpost",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="contentpostimage",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_content_feed' AND model = 'contentpostimage'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="5c5fa02ff7e87080bae19806da46923640a58bdc",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_ce024",
                    table="baseapp_content_feed_contentpostimage",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="contentpostimage",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_content_feed' AND model = 'contentpostimage')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="cdcaff45dc47fb4f47e49432b7e28ac482655aaa",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_867c3",
                    table="baseapp_content_feed_contentpostimage",
                    when="AFTER",
                ),
            ),
        ),
    ]
