# Generated by Django 5.2.12 on 2026-05-07 17:24
#
# Drops the legacy `reactions_count` / `is_reactions_enabled` columns from the
# un-swapped concrete `baseapp_content_feed.ContentPost` table. Both values now
# live on `baseapp_reactions.ReactableMetadata` keyed by `DocumentId`.
#
# Projects using the un-swapped table that need to preserve existing reaction
# data should add their own `RunPython` operation calling
# `baseapp_reactions.migration_helpers.convert_legacy_reactable_fields_to_metadata_helper.migrate_legacy_reactable_fields_to_metadata`
# *before* this migration runs (and depend on `baseapp_core.0001_initial` plus
# whatever migration creates their `ReactableMetadata` table). Projects that
# swap `ContentPost` should run the equivalent migration in their swap target
# instead — this migration is a no-op for them.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_content_feed", "0005_contentpost_is_reactions_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentpost",
            name="is_reactions_enabled",
        ),
        migrations.RemoveField(
            model_name="contentpost",
            name="reactions_count",
        ),
    ]
