# Generated by Django 5.1.11 on 2025-09-15 14:28

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_organizations", "0003_alter_organization_profile"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="organization",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_publicidmapping (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_organizations' AND model = 'organization'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="e5cb7bf8be00f46d87e4b2dd2acaec49082d48cf",
                    operation="INSERT",
                    pgid="pgtrigger_insert_public_id_mapping_bbe88",
                    table="baseapp_organizations_organization",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="organization",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_organizations' AND model = 'organization')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="fde4bbb96c929543eadcdf88b677cecc37a26730",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_3480f",
                    table="baseapp_organizations_organization",
                    when="AFTER",
                ),
            ),
        ),
    ]
