# Generated by Django 5.1.14 on 2025-12-03 04:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_organizations", "0003_alter_organization_profile"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="organization",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_organizations' AND model = 'organization'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="ecf8c57f626483effe6e1a4997cbb5afea69cf2d",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_c9128",
                    table="baseapp_organizations_organization",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="organization",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_organizations' AND model = 'organization')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="9c5d37cb613536d223d259fa30a588269415d386",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_47310",
                    table="baseapp_organizations_organization",
                    when="AFTER",
                ),
            ),
        ),
    ]
