# Generated by Django 5.2.14 on 2026-06-08 13:03

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import baseapp_reactions.migration_helpers.convert_reactions_gfk_into_document_id_helper
import baseapp_reactions.models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("reactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReactableMetadata",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "target",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="reactable_metadata",
                        serialize=False,
                        to="baseapp_core.documentid",
                    ),
                ),
                (
                    "reactions_count",
                    models.JSONField(
                        default=baseapp_reactions.models.default_reactions_count, editable=False
                    ),
                ),
                ("is_reactions_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "reactable metadata",
                "verbose_name_plural": "reactable metadata",
                "abstract": False,
                "swappable": "BASEAPP_REACTIONS_REACTABLEMETADATA_MODEL",
            },
        ),
        migrations.AddField(
            model_name="reaction",
            name="target_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions_inbox",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.RunPython(
            code=baseapp_reactions.migration_helpers.convert_reactions_gfk_into_document_id_helper.migrate_reaction_targets_to_document_id,
            reverse_code=baseapp_reactions.migration_helpers.convert_reactions_gfk_into_document_id_helper.reverse_migrate_reaction_targets_to_generic_fk,
        ),
        migrations.AlterField(
            model_name="reaction",
            name="target_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions_inbox",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together=set(),
        ),
        migrations.RemoveIndex(
            model_name="reaction",
            name="reactions_r_target__09ad9c_idx",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="target_content_type",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="target_object_id",
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("profile", "target_document")},
        ),
        migrations.AlterField(
            model_name="reactablemetadata",
            name="target",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="baseapp_core.documentid",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="target_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
    ]
