# Generated by Django 5.2.12 on 2026-05-07 17:13

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import baseapp_reactions.models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("reactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReactableMetadata",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "target",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="reactable_metadata",
                        serialize=False,
                        to="baseapp_core.documentid",
                    ),
                ),
                (
                    "reactions_count",
                    models.JSONField(
                        default=baseapp_reactions.models.default_reactions_count, editable=False
                    ),
                ),
                ("is_reactions_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "reactable metadata",
                "verbose_name_plural": "reactable metadata",
                "abstract": False,
                "swappable": "BASEAPP_REACTIONS_REACTABLEMETADATA_MODEL",
            },
        ),
    ]
