# Generated by Django 5.1.11 on 2025-09-15 14:28

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_follows", "0007_alter_follow_unique_together"),
        ("baseapp_core", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="follow",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_publicidmapping (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_follows' AND model = 'follow'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="caf76146d536965e2bbbfa2e32d2b8e026478051",
                    operation="INSERT",
                    pgid="pgtrigger_insert_public_id_mapping_79f92",
                    table="baseapp_follows_follow",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="follow",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_follows' AND model = 'follow')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="920f250541341c1406b38fb82f3ce705d2bb3605",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_90d36",
                    table="baseapp_follows_follow",
                    when="AFTER",
                ),
            ),
        ),
    ]
