# Generated by Django 5.1.11 on 2025-09-11 18:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_follows", "0007_alter_follow_unique_together"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="follow",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_follows' AND model = 'follow')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="920f250541341c1406b38fb82f3ce705d2bb3605",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_90d36",
                    table="baseapp_follows_follow",
                    when="AFTER",
                ),
            ),
        ),
    ]
