# Generated by Django 5.1.14 on 2025-12-03 04:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_follows", "0007_alter_follow_unique_together"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="follow",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_follows' AND model = 'follow'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="faf060f08ad016d23a07b65b7f4a5f372c20d4d8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_44b6a",
                    table="baseapp_follows_follow",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="follow",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_follows' AND model = 'follow')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="67b212e47323149159200fe575b58435631fde29",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_8d538",
                    table="baseapp_follows_follow",
                    when="AFTER",
                ),
            ),
        ),
    ]
