# Generated by Django 5.2.12 on 2026-03-20 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("baseapp_follows", "0008_create_followstats_remap_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="baseapp_core.documentid",
                verbose_name="actor",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="baseapp_core.documentid",
                verbose_name="target",
            ),
        ),
    ]
