# Generated by Django 4.2.3 on 2023-12-19 02:42

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_files", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="file",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="file",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="fileevent",
            name="pgh_operation",
            field=models.IntegerField(
                choices=[
                    (1, "Insert"),
                    (2, "Update"),
                    (3, "Delete"),
                    (4, "Insertorupdate"),
                ],
                null=True,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "baseapp_files_fileevent" ("content_type", "created", "created_by_id", "description", "file", "file_name", "file_size", "id", "modified", "name", "parent_content_type_id", "parent_object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "updated") VALUES (NEW."content_type", NEW."created", NEW."created_by_id", NEW."description", NEW."file", NEW."file_name", NEW."file_size", NEW."id", NEW."modified", NEW."name", NEW."parent_content_type_id", NEW."parent_object_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", 1, NEW."updated"); RETURN NULL;',
                    hash="df20bf9549839bb058bec50b2ec00b48b1dcb66c",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_03cf9",
                    table="baseapp_files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "baseapp_files_fileevent" ("content_type", "created", "created_by_id", "description", "file", "file_name", "file_size", "id", "modified", "name", "parent_content_type_id", "parent_object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "updated") VALUES (NEW."content_type", NEW."created", NEW."created_by_id", NEW."description", NEW."file", NEW."file_name", NEW."file_size", NEW."id", NEW."modified", NEW."name", NEW."parent_content_type_id", NEW."parent_object_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", 2, NEW."updated"); RETURN NULL;',
                    hash="a4b2ac3b6afa90f1fb04a72fd1d2a81064d6824d",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_11b9c",
                    table="baseapp_files_file",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="file",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "baseapp_files_fileevent" ("content_type", "created", "created_by_id", "description", "file", "file_name", "file_size", "id", "modified", "name", "parent_content_type_id", "parent_object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "updated") VALUES (OLD."content_type", OLD."created", OLD."created_by_id", OLD."description", OLD."file", OLD."file_name", OLD."file_size", OLD."id", OLD."modified", OLD."name", OLD."parent_content_type_id", OLD."parent_object_id", _pgh_attach_context(), NOW(), \'snapshot\', OLD."id", 3, OLD."updated"); RETURN NULL;',
                    hash="ce527d470682a74377bb63ac788dc32f5d10a52f",
                    operation="DELETE",
                    pgid="pgtrigger_snapshot_delete_09e63",
                    table="baseapp_files_file",
                    when="AFTER",
                ),
            ),
        ),
    ]
