# Generated by Django 5.1.13 on 2025-11-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_files", "0003_migrate_data_to_filetarget"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="filetarget",
            new_name="baseapp_fil_target__2487dc_idx",
            old_name="baseapp_fil_target__9f3b9c_idx",
        ),
    ]
