# Generated by Django 5.1.13 on 2025-10-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cache", "0004_alter_socialauthaccesstokencache_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialauthaccesstokencache",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
