# Generated by Django 5.1.14 on 2025-12-09 05:15

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public-facing UUID identifier",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        help_text="The primary key of the mapped object"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The model type this UUID maps to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document ID",
                "verbose_name_plural": "Document IDs",
                "indexes": [
                    models.Index(fields=["public_id"], name="baseapp_cor_public__efe672_idx")
                ],
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
