# Generated by Django 5.1.11 on 2025-09-02 20:10

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        CreateExtension("pgcrypto"),
        migrations.CreateModel(
            name="PublicIdMapping",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public-facing UUID identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        help_text="The primary key of the mapped object"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The model type this UUID maps to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public ID Mapping",
                "verbose_name_plural": "Public ID Mappings",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="baseapp_cor_content_3fcad4_idx"
                    ),
                    models.Index(fields=["public_id"], name="baseapp_cor_public__e4b414_idx"),
                ],
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
