# Generated by Django 5.1.11 on 2025-11-17 15:01

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentId",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("object_id", models.PositiveBigIntegerField(db_index=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "db_table": "baseapp_core_documentid",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="baseapp_cor_content_9946f4_idx"
                    )
                ],
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
