# Generated by Django 4.2.13 on 2024-06-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cache", "0003_alter_socialauthaccesstokencache_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialauthaccesstokencache",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
