# Generated by Django 5.1.13 on 2025-11-14 10:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pghistory", "0006_delete_aggregateevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoJSONFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        help_text="Geographic data in any geometry type (Point, LineString, Polygon, etc.)",
                        srid=4326,
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this feature",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geojson_features",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GeoJSON Feature",
                "verbose_name_plural": "GeoJSON Features",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GeoJSONFeatureEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        help_text="Geographic data in any geometry type (Point, LineString, Polygon, etc.)",
                        srid=4326,
                    ),
                ),
                ("target_object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to=settings.BASEAPP_MAPS_GEOJSONFEATURE_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who created this feature",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="geojsonfeature",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="maps_geojso_target__dbdfff_idx",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="geojsonfeature",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "maps_geojsonfeatureevent" ("created", "geometry", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_content_type_id", "target_object_id", "user_id") VALUES (NEW."created", NEW."geometry", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."target_content_type_id", NEW."target_object_id", NEW."user_id"); RETURN NULL;',
                    hash="59bdeb0c25aee712c846dc925e49635d450fccd3",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_64bc6",
                    table="maps_geojsonfeature",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="geojsonfeature",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."geometry" IS DISTINCT FROM (NEW."geometry") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."target_content_type_id" IS DISTINCT FROM (NEW."target_content_type_id") OR OLD."target_object_id" IS DISTINCT FROM (NEW."target_object_id") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func='INSERT INTO "maps_geojsonfeatureevent" ("created", "geometry", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_content_type_id", "target_object_id", "user_id") VALUES (NEW."created", NEW."geometry", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."target_content_type_id", NEW."target_object_id", NEW."user_id"); RETURN NULL;',
                    hash="d31f7b73b7edda5991c62859122a4ba3618504f0",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d864f",
                    table="maps_geojsonfeature",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="geojsonfeature",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "maps_geojsonfeatureevent" ("created", "geometry", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_content_type_id", "target_object_id", "user_id") VALUES (OLD."created", OLD."geometry", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."target_content_type_id", OLD."target_object_id", OLD."user_id"); RETURN NULL;',
                    hash="4001850f7f3c51a752df21819c4a81dd95262f6e",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_76557",
                    table="maps_geojsonfeature",
                    when="AFTER",
                ),
            ),
        ),
    ]
