# Generated by Django 3.2.19 on 2023-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0005_user_password_changed_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
