# Generated by Django 5.1.15 on 2025-12-24 14:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import baseapp_core.models
import baseapp_reactions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "reactions_count",
                    models.JSONField(
                        default=baseapp_reactions.models.default_reactions_count, editable=False
                    ),
                ),
                ("is_reactions_enabled", models.BooleanField(default=True)),
                ("content", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_posts",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                        verbose_name="profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ContentPostImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=baseapp_core.models.random_name_in("content_feed_images"),
                        verbose_name="image",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.BASEAPP_CONTENT_FEED_CONTENTPOST_MODEL,
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="contentpost",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'content_feed' AND model = 'contentpost'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="f277a483b9eeff21c7d414745c2978745497fa6a",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_04993",
                    table="content_feed_contentpost",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="contentpost",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'content_feed' AND model = 'contentpost')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="95e6442ac265294b41dc69719de5d022255ff42d",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_7b150",
                    table="content_feed_contentpost",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="contentpostimage",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'content_feed' AND model = 'contentpostimage'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="0ec1151e5e59bb2455c43a7e4000927ff4dff4cd",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_61f57",
                    table="content_feed_contentpostimage",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="contentpostimage",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'content_feed' AND model = 'contentpostimage')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="2329c205c4aaf5022eb14ed25c4f89fd5f78c8e8",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_81a84",
                    table="content_feed_contentpostimage",
                    when="AFTER",
                ),
            ),
        ),
    ]
