# Generated by Django 5.2.12 on 2026-04-27 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_feed", "0001_initial"),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpost",
            name="mentioned_profiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_mentions",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                verbose_name="mentioned profiles",
            ),
        ),
    ]
