# Generated by Django 5.2.12 on 2026-05-07 17:24

from django.db import migrations

from baseapp_reactions.migration_helpers.convert_legacy_reactable_fields_to_metadata_helper import (
    migrate_legacy_reactable_fields_to_metadata,
    reverse_migrate_legacy_reactable_fields_from_metadata,
)


def migrate_contentpost_reactable_fields(apps, schema_editor):
    migrate_legacy_reactable_fields_to_metadata(
        apps,
        schema_editor,
        source_app_label="content_feed",
        source_model_name="ContentPost",
        metadata_app_label="reactions",
    )


def reverse_migrate_contentpost_reactable_fields(apps, schema_editor):
    reverse_migrate_legacy_reactable_fields_from_metadata(
        apps,
        schema_editor,
        source_app_label="content_feed",
        source_model_name="ContentPost",
        metadata_app_label="reactions",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("content_feed", "0001_initial"),
        ("reactions", "0002_plugin_arch_squashed"),
    ]

    operations = [
        migrations.RunPython(
            migrate_contentpost_reactable_fields,
            reverse_migrate_contentpost_reactable_fields,
        ),
        migrations.RemoveField(
            model_name="contentpost",
            name="is_reactions_enabled",
        ),
        migrations.RemoveField(
            model_name="contentpost",
            name="reactions_count",
        ),
    ]
