# Generated by Django 5.2.14 on 2026-06-08 13:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.apps import apps as django_apps
from django.conf import settings
from django.db import migrations, models

import baseapp_comments.migration_helpers.convert_comments_gfk_into_document_id_helper
import baseapp_comments.models
from baseapp_comments.migration_helpers.convert_legacy_commentable_fields_into_metadata_helper import (
    migrate_legacy_commentable_fields_to_metadata,
    reverse_migrate_legacy_commentable_fields_from_metadata,
)
from baseapp_reactions.migration_helpers.convert_legacy_reactable_fields_to_metadata_helper import (
    migrate_legacy_reactable_fields_to_metadata,
    reverse_migrate_legacy_reactable_fields_from_metadata,
)


def migrate_comment_commentable_to_metadata(apps, schema_editor):
    migrate_legacy_commentable_fields_to_metadata(
        apps,
        schema_editor,
        source_app_label="comments",
        source_model_name="Comment",
    )


def reverse_migrate_comment_commentable_from_metadata(apps, schema_editor):
    reverse_migrate_legacy_commentable_fields_from_metadata(
        apps,
        schema_editor,
        source_app_label="comments",
        source_model_name="Comment",
    )


def migrate_comment_reports_count(apps, schema_editor):
    # ReportableMetadata only exists when baseapp_reports is installed; skip the
    # backfill otherwise. The column removal / trigger regen below run regardless.
    try:
        apps.get_model("reports", "ReportableMetadata")
    except LookupError:
        return

    from baseapp_reports.migration_helpers.convert_legacy_reports_count_to_metadata_helper import (
        migrate_legacy_reports_count_to_metadata,
    )

    migrate_legacy_reports_count_to_metadata(
        apps,
        schema_editor,
        source_app_label="comments",
        source_model_name="Comment",
        metadata_app_label="reports",
    )


def reverse_migrate_comment_reports_count(apps, schema_editor):
    try:
        apps.get_model("reports", "ReportableMetadata")
    except LookupError:
        return

    from baseapp_reports.migration_helpers.convert_legacy_reports_count_to_metadata_helper import (
        reverse_migrate_legacy_reports_count_from_metadata,
    )

    reverse_migrate_legacy_reports_count_from_metadata(
        apps,
        schema_editor,
        source_app_label="comments",
        source_model_name="Comment",
        metadata_app_label="reports",
    )


def migrate_comment_reactable_fields(apps, schema_editor):
    migrate_legacy_reactable_fields_to_metadata(
        apps,
        schema_editor,
        source_app_label="comments",
        source_model_name="Comment",
        metadata_app_label="reactions",
    )


def reverse_migrate_comment_reactable_fields(apps, schema_editor):
    reverse_migrate_legacy_reactable_fields_from_metadata(
        apps,
        schema_editor,
        source_app_label="comments",
        source_model_name="Comment",
        metadata_app_label="reactions",
    )


def _dependencies():
    # reports is optional (app-disable support); depend on it only when installed.
    deps = [
        ("baseapp_core", "0001_initial"),
        ("comments", "0001_initial"),
        ("profiles", "__first__"),
        ("reactions", "0002_reactablemetadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    if "reports" in django_apps.app_configs:
        deps.append(("reports", "0002_reportablemetadata"))
    return deps


class Migration(migrations.Migration):

    replaces = [
        ("comments", "0002_commentablemetadata"),
        ("comments", "0003_migrate_comment_commentable_to_metadata_remove_comment_mixin"),
        ("comments", "0004_remove_comment_insert_insert_and_more"),
        ("comments", "0005_remove_reports_count"),
        ("comments", "0006_remove_reactions_legacy_columns"),
        ("comments", "0007_alter_comment_target_document_and_more"),
        ("comments", "0008_alter_commentablemetadata_target"),
        ("comments", "0009_alter_comment_target_document"),
    ]

    dependencies = _dependencies()

    operations = [
        migrations.CreateModel(
            name="CommentableMetadata",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "target",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="commentable_metadata",
                        serialize=False,
                        to="baseapp_core.documentid",
                    ),
                ),
                (
                    "comments_count",
                    models.JSONField(
                        default=baseapp_comments.models.default_comments_count,
                        editable=False,
                        verbose_name="comments count",
                    ),
                ),
                (
                    "is_comments_enabled",
                    models.BooleanField(default=True, verbose_name="is comments enabled"),
                ),
            ],
            options={
                "verbose_name": "commentable metadata",
                "verbose_name_plural": "commentable metadata",
                "abstract": False,
                "swappable": "BASEAPP_COMMENTS_COMMENTABLEMETADATA_MODEL",
            },
        ),
        migrations.RunPython(
            code=migrate_comment_commentable_to_metadata,
            reverse_code=reverse_migrate_comment_commentable_from_metadata,
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="delete_delete",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="is_comments_enabled",
        ),
        migrations.RemoveField(
            model_name="commentevent",
            name="is_comments_enabled",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "reports_count", "status", "target_content_type_id", "target_object_id", "user_id") VALUES (NEW."body", NEW."created", NEW."id", NEW."in_reply_to_id", NEW."is_edited", NEW."is_pinned", NEW."is_reactions_enabled", NEW."language", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."profile_id", NEW."reports_count", NEW."status", NEW."target_content_type_id", NEW."target_object_id", NEW."user_id"); RETURN NULL;',
                    hash="67dba742c66fb15c3830c2f36a2b316009903b3e",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_18fd9",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."body" IS DISTINCT FROM (NEW."body") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."in_reply_to_id" IS DISTINCT FROM (NEW."in_reply_to_id") OR OLD."is_edited" IS DISTINCT FROM (NEW."is_edited") OR OLD."is_pinned" IS DISTINCT FROM (NEW."is_pinned") OR OLD."is_reactions_enabled" IS DISTINCT FROM (NEW."is_reactions_enabled") OR OLD."language" IS DISTINCT FROM (NEW."language") OR OLD."profile_id" IS DISTINCT FROM (NEW."profile_id") OR OLD."reports_count" IS DISTINCT FROM (NEW."reports_count") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."target_content_type_id" IS DISTINCT FROM (NEW."target_content_type_id") OR OLD."target_object_id" IS DISTINCT FROM (NEW."target_object_id") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "reports_count", "status", "target_content_type_id", "target_object_id", "user_id") VALUES (NEW."body", NEW."created", NEW."id", NEW."in_reply_to_id", NEW."is_edited", NEW."is_pinned", NEW."is_reactions_enabled", NEW."language", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."profile_id", NEW."reports_count", NEW."status", NEW."target_content_type_id", NEW."target_object_id", NEW."user_id"); RETURN NULL;',
                    hash="ead734b59c220efdd0a54901be04af7d64436419",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_230ec",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "reports_count", "status", "target_content_type_id", "target_object_id", "user_id") VALUES (OLD."body", OLD."created", OLD."id", OLD."in_reply_to_id", OLD."is_edited", OLD."is_pinned", OLD."is_reactions_enabled", OLD."language", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."profile_id", OLD."reports_count", OLD."status", OLD."target_content_type_id", OLD."target_object_id", OLD."user_id"); RETURN NULL;',
                    hash="871e9fa6745bcc3fe3ba7ad9c6203f33ebb7161a",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_ff62f",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="delete_delete",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="comments_co_target__9b7cc1_idx",
        ),
        migrations.AddField(
            model_name="comment",
            name="target_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_inbox",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.AddField(
            model_name="commentevent",
            name="target_document",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.RunPython(
            code=baseapp_comments.migration_helpers.convert_comments_gfk_into_document_id_helper.migrate_comment_targets_to_document_id,
            reverse_code=baseapp_comments.migration_helpers.convert_comments_gfk_into_document_id_helper.reverse_migrate_comment_targets_to_generic_fk,
        ),
        migrations.AlterField(
            model_name="comment",
            name="target_document",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_inbox",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.AlterField(
            model_name="commentevent",
            name="target_document",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.RemoveField(
            model_name="comment",
            name="target_content_type",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="target_object_id",
        ),
        migrations.RemoveField(
            model_name="commentevent",
            name="target_content_type",
        ),
        migrations.RemoveField(
            model_name="commentevent",
            name="target_object_id",
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["target_document", "status", "-is_pinned", "-created"],
                name="comments_co_target__815b05_idx",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "reports_count", "status", "target_document_id", "user_id") VALUES (NEW."body", NEW."created", NEW."id", NEW."in_reply_to_id", NEW."is_edited", NEW."is_pinned", NEW."is_reactions_enabled", NEW."language", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."profile_id", NEW."reports_count", NEW."status", NEW."target_document_id", NEW."user_id"); RETURN NULL;',
                    hash="88555d6b961c25e47ed728add1e0998d363a178d",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_18fd9",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."body" IS DISTINCT FROM (NEW."body") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."in_reply_to_id" IS DISTINCT FROM (NEW."in_reply_to_id") OR OLD."is_edited" IS DISTINCT FROM (NEW."is_edited") OR OLD."is_pinned" IS DISTINCT FROM (NEW."is_pinned") OR OLD."is_reactions_enabled" IS DISTINCT FROM (NEW."is_reactions_enabled") OR OLD."language" IS DISTINCT FROM (NEW."language") OR OLD."profile_id" IS DISTINCT FROM (NEW."profile_id") OR OLD."reports_count" IS DISTINCT FROM (NEW."reports_count") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."target_document_id" IS DISTINCT FROM (NEW."target_document_id") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "reports_count", "status", "target_document_id", "user_id") VALUES (NEW."body", NEW."created", NEW."id", NEW."in_reply_to_id", NEW."is_edited", NEW."is_pinned", NEW."is_reactions_enabled", NEW."language", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."profile_id", NEW."reports_count", NEW."status", NEW."target_document_id", NEW."user_id"); RETURN NULL;',
                    hash="b49b31df14ef89ae900ebbbd6ed77c8ea0fab85e",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_230ec",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "reports_count", "status", "target_document_id", "user_id") VALUES (OLD."body", OLD."created", OLD."id", OLD."in_reply_to_id", OLD."is_edited", OLD."is_pinned", OLD."is_reactions_enabled", OLD."language", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."profile_id", OLD."reports_count", OLD."status", OLD."target_document_id", OLD."user_id"); RETURN NULL;',
                    hash="9c8f902da221fd8e9cc2eb147b049b4f9d6aa05c",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_ff62f",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="delete_delete",
        ),
        migrations.RunPython(
            code=migrate_comment_reports_count,
            reverse_code=reverse_migrate_comment_reports_count,
        ),
        migrations.RemoveField(
            model_name="comment",
            name="reports_count",
        ),
        migrations.RemoveField(
            model_name="commentevent",
            name="reports_count",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "status", "target_document_id", "user_id") VALUES (NEW."body", NEW."created", NEW."id", NEW."in_reply_to_id", NEW."is_edited", NEW."is_pinned", NEW."is_reactions_enabled", NEW."language", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."profile_id", NEW."status", NEW."target_document_id", NEW."user_id"); RETURN NULL;',
                    hash="88871de97b5a540afdc480809cc84c8d8c502ac8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_18fd9",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."body" IS DISTINCT FROM (NEW."body") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."in_reply_to_id" IS DISTINCT FROM (NEW."in_reply_to_id") OR OLD."is_edited" IS DISTINCT FROM (NEW."is_edited") OR OLD."is_pinned" IS DISTINCT FROM (NEW."is_pinned") OR OLD."is_reactions_enabled" IS DISTINCT FROM (NEW."is_reactions_enabled") OR OLD."language" IS DISTINCT FROM (NEW."language") OR OLD."profile_id" IS DISTINCT FROM (NEW."profile_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."target_document_id" IS DISTINCT FROM (NEW."target_document_id") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "status", "target_document_id", "user_id") VALUES (NEW."body", NEW."created", NEW."id", NEW."in_reply_to_id", NEW."is_edited", NEW."is_pinned", NEW."is_reactions_enabled", NEW."language", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."profile_id", NEW."status", NEW."target_document_id", NEW."user_id"); RETURN NULL;',
                    hash="e327bd9facdcc2f28305001ded5e71cf98d8f541",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_230ec",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "status", "target_document_id", "user_id") VALUES (OLD."body", OLD."created", OLD."id", OLD."in_reply_to_id", OLD."is_edited", OLD."is_pinned", OLD."is_reactions_enabled", OLD."language", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."profile_id", OLD."status", OLD."target_document_id", OLD."user_id"); RETURN NULL;',
                    hash="deb222705643ed01960b5428e8e4b0ff2a8478dc",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_ff62f",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="delete_delete",
        ),
        migrations.RunPython(
            code=migrate_comment_reactable_fields,
            reverse_code=reverse_migrate_comment_reactable_fields,
        ),
        migrations.RemoveField(
            model_name="comment",
            name="is_reactions_enabled",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="reactions_count",
        ),
        migrations.RemoveField(
            model_name="commentevent",
            name="is_reactions_enabled",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "status", "target_document_id", "user_id") VALUES (NEW."body", NEW."created", NEW."id", NEW."in_reply_to_id", NEW."is_edited", NEW."is_pinned", NEW."language", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."profile_id", NEW."status", NEW."target_document_id", NEW."user_id"); RETURN NULL;',
                    hash="65bae7928bdc689e0e7b241674e5a550c1d2fc6f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_18fd9",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."body" IS DISTINCT FROM (NEW."body") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."in_reply_to_id" IS DISTINCT FROM (NEW."in_reply_to_id") OR OLD."is_edited" IS DISTINCT FROM (NEW."is_edited") OR OLD."is_pinned" IS DISTINCT FROM (NEW."is_pinned") OR OLD."language" IS DISTINCT FROM (NEW."language") OR OLD."profile_id" IS DISTINCT FROM (NEW."profile_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."target_document_id" IS DISTINCT FROM (NEW."target_document_id") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "status", "target_document_id", "user_id") VALUES (NEW."body", NEW."created", NEW."id", NEW."in_reply_to_id", NEW."is_edited", NEW."is_pinned", NEW."language", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."profile_id", NEW."status", NEW."target_document_id", NEW."user_id"); RETURN NULL;',
                    hash="bd650c3bca31bdcbe564049530395b03c8294dc6",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_230ec",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "status", "target_document_id", "user_id") VALUES (OLD."body", OLD."created", OLD."id", OLD."in_reply_to_id", OLD."is_edited", OLD."is_pinned", OLD."language", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."profile_id", OLD."status", OLD."target_document_id", OLD."user_id"); RETURN NULL;',
                    hash="6535b840614d7cd1952f89fbd0d01a33753469d4",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_ff62f",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AlterField(
            model_name="commentevent",
            name="target_document",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.AlterField(
            model_name="commentablemetadata",
            name="target",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="baseapp_core.documentid",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="target_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
    ]
