# Generated by Django 5.2.12 on 2026-04-22 19:27

import django.db.models.deletion
from django.db import migrations, models

import baseapp_comments.models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentableMetadata",
            fields=[
                (
                    "target",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="commentable_metadata",
                        serialize=False,
                        to="baseapp_core.documentid",
                    ),
                ),
                (
                    "comments_count",
                    models.JSONField(
                        default=baseapp_comments.models.default_comments_count,
                        editable=False,
                        verbose_name="comments count",
                    ),
                ),
                (
                    "is_comments_enabled",
                    models.BooleanField(default=True, verbose_name="is comments enabled"),
                ),
            ],
            options={
                "verbose_name": "commentable metadata",
                "verbose_name_plural": "commentable metadata",
                "abstract": False,
                "swappable": "BASEAPP_COMMENTS_COMMENTABLEMETADATA_MODEL",
            },
        ),
    ]
