# Generated by Django 5.1.15 on 2025-12-24 14:28

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_comment_profile"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'comments' AND model = 'comment'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="0e1541c7dba6d595403f71a8324e45749e077f01",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_79da0",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'comments' AND model = 'comment')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="24b0be10ef293cd2af90260fd22ff3b0c12580f9",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_f6e07",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
    ]
