# Generated by Django 5.1.13 on 2025-10-23 19:39

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models

import baseapp.files.utils


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_comment_profile"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="comment",
            name="files_count",
            field=models.JSONField(default=baseapp.files.utils.default_files_count),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_files_enabled",
            field=models.BooleanField(default=True, verbose_name="is files enabled"),
        ),
        migrations.AddField(
            model_name="commentevent",
            name="files_count",
            field=models.JSONField(default=baseapp.files.utils.default_files_count),
        ),
        migrations.AddField(
            model_name="commentevent",
            name="is_files_enabled",
            field=models.BooleanField(default=True, verbose_name="is files enabled"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "files_count", "id", "in_reply_to_id", "is_comments_enabled", "is_edited", "is_files_enabled", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "reports_count", "status", "target_content_type_id", "target_object_id", "user_id") VALUES (NEW."body", NEW."created", NEW."files_count", NEW."id", NEW."in_reply_to_id", NEW."is_comments_enabled", NEW."is_edited", NEW."is_files_enabled", NEW."is_pinned", NEW."is_reactions_enabled", NEW."language", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."profile_id", NEW."reports_count", NEW."status", NEW."target_content_type_id", NEW."target_object_id", NEW."user_id"); RETURN NULL;',
                    hash="848cd584d0851dfba0d80d85a577b699c15fca30",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_18fd9",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."body" IS DISTINCT FROM (NEW."body") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."files_count" IS DISTINCT FROM (NEW."files_count") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."in_reply_to_id" IS DISTINCT FROM (NEW."in_reply_to_id") OR OLD."is_comments_enabled" IS DISTINCT FROM (NEW."is_comments_enabled") OR OLD."is_edited" IS DISTINCT FROM (NEW."is_edited") OR OLD."is_files_enabled" IS DISTINCT FROM (NEW."is_files_enabled") OR OLD."is_pinned" IS DISTINCT FROM (NEW."is_pinned") OR OLD."is_reactions_enabled" IS DISTINCT FROM (NEW."is_reactions_enabled") OR OLD."language" IS DISTINCT FROM (NEW."language") OR OLD."profile_id" IS DISTINCT FROM (NEW."profile_id") OR OLD."reports_count" IS DISTINCT FROM (NEW."reports_count") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."target_content_type_id" IS DISTINCT FROM (NEW."target_content_type_id") OR OLD."target_object_id" IS DISTINCT FROM (NEW."target_object_id") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func='INSERT INTO "comments_commentevent" ("body", "created", "files_count", "id", "in_reply_to_id", "is_comments_enabled", "is_edited", "is_files_enabled", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "reports_count", "status", "target_content_type_id", "target_object_id", "user_id") VALUES (NEW."body", NEW."created", NEW."files_count", NEW."id", NEW."in_reply_to_id", NEW."is_comments_enabled", NEW."is_edited", NEW."is_files_enabled", NEW."is_pinned", NEW."is_reactions_enabled", NEW."language", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."profile_id", NEW."reports_count", NEW."status", NEW."target_content_type_id", NEW."target_object_id", NEW."user_id"); RETURN NULL;',
                    hash="f064da2ba0d6bdb30f7e1ccc875e87ca67687492",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_230ec",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "files_count", "id", "in_reply_to_id", "is_comments_enabled", "is_edited", "is_files_enabled", "is_pinned", "is_reactions_enabled", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "reports_count", "status", "target_content_type_id", "target_object_id", "user_id") VALUES (OLD."body", OLD."created", OLD."files_count", OLD."id", OLD."in_reply_to_id", OLD."is_comments_enabled", OLD."is_edited", OLD."is_files_enabled", OLD."is_pinned", OLD."is_reactions_enabled", OLD."language", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."profile_id", OLD."reports_count", OLD."status", OLD."target_content_type_id", OLD."target_object_id", OLD."user_id"); RETURN NULL;',
                    hash="ab8e511ea03b6a455b5d028f0a002c4165d4769f",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_ff62f",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
    ]
