# Generated by Django 5.1.11 on 2025-09-15 14:28

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_comment_profile"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_publicidmapping (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'comments' AND model = 'comment'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="61a4f97d1ec561059a960076d07bc3d1447d3b9b",
                    operation="INSERT",
                    pgid="pgtrigger_insert_public_id_mapping_cdd7a",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'comments' AND model = 'comment')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="5b4f4c1ab6daab5857f3835b1aac93228845212b",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_4c693",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
    ]
