# Generated by Django 5.2.12 on 2026-05-07 17:24

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations

from baseapp_reactions.migration_helpers.convert_legacy_reactable_fields_to_metadata_helper import (
    migrate_legacy_reactable_fields_to_metadata,
    reverse_migrate_legacy_reactable_fields_from_metadata,
)


def migrate_comment_reactable_fields(apps, schema_editor):
    migrate_legacy_reactable_fields_to_metadata(
        apps,
        schema_editor,
        source_app_label="comments",
        source_model_name="Comment",
        metadata_app_label="reactions",
    )


def reverse_migrate_comment_reactable_fields(apps, schema_editor):
    reverse_migrate_legacy_reactable_fields_from_metadata(
        apps,
        schema_editor,
        source_app_label="comments",
        source_model_name="Comment",
        metadata_app_label="reactions",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_remove_reports_count"),
        ("reactions", "0002_reactablemetadata"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="comment",
            name="delete_delete",
        ),
        migrations.RunPython(
            migrate_comment_reactable_fields,
            reverse_migrate_comment_reactable_fields,
        ),
        migrations.RemoveField(
            model_name="comment",
            name="is_reactions_enabled",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="reactions_count",
        ),
        migrations.RemoveField(
            model_name="commentevent",
            name="is_reactions_enabled",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "status", "target_document_id", "user_id") VALUES (NEW."body", NEW."created", NEW."id", NEW."in_reply_to_id", NEW."is_edited", NEW."is_pinned", NEW."language", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."profile_id", NEW."status", NEW."target_document_id", NEW."user_id"); RETURN NULL;',
                    hash="65bae7928bdc689e0e7b241674e5a550c1d2fc6f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_18fd9",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."body" IS DISTINCT FROM (NEW."body") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."in_reply_to_id" IS DISTINCT FROM (NEW."in_reply_to_id") OR OLD."is_edited" IS DISTINCT FROM (NEW."is_edited") OR OLD."is_pinned" IS DISTINCT FROM (NEW."is_pinned") OR OLD."language" IS DISTINCT FROM (NEW."language") OR OLD."profile_id" IS DISTINCT FROM (NEW."profile_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."target_document_id" IS DISTINCT FROM (NEW."target_document_id") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "status", "target_document_id", "user_id") VALUES (NEW."body", NEW."created", NEW."id", NEW."in_reply_to_id", NEW."is_edited", NEW."is_pinned", NEW."language", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."profile_id", NEW."status", NEW."target_document_id", NEW."user_id"); RETURN NULL;',
                    hash="bd650c3bca31bdcbe564049530395b03c8294dc6",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_230ec",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comments_commentevent" ("body", "created", "id", "in_reply_to_id", "is_edited", "is_pinned", "language", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_id", "status", "target_document_id", "user_id") VALUES (OLD."body", OLD."created", OLD."id", OLD."in_reply_to_id", OLD."is_edited", OLD."is_pinned", OLD."language", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."profile_id", OLD."status", OLD."target_document_id", OLD."user_id"); RETURN NULL;',
                    hash="6535b840614d7cd1952f89fbd0d01a33753469d4",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_ff62f",
                    table="comments_comment",
                    when="AFTER",
                ),
            ),
        ),
    ]
