# Generated by Django 5.2.14 on 2026-05-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("comments", "0006_remove_reactions_legacy_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="target_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_inbox",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.AlterField(
            model_name="commentevent",
            name="target_document",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
    ]
