# Generated by Django 5.0.8 on 2025-03-25 21:40

from django.db import migrations, models

import baseapp_comments.models
import baseapp_wagtail.base.stream_fields.page_body_stream_field


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardpage",
            name="comments_count",
            field=models.JSONField(
                default=baseapp_comments.models.default_comments_count,
                editable=False,
                verbose_name="comments count",
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="is_comments_enabled",
            field=models.BooleanField(default=True, verbose_name="is comments enabled"),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=baseapp_wagtail.base.stream_fields.page_body_stream_field.PageBodyStreamField(
                [("section_stream_block", 8)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True, "use_json_field": True},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ul", "hr"],
                            "icon": "pilcrow",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {"admin_text": "<hr />", "label": " "},
                    ),
                    4: (
                        "baseapp_wagtail.base.blocks.basic_blocks.custom_image_chooser_block.block.CustomImageChooserBlock",
                        (),
                        {"label": " ", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [("left", "Left"), ("right", "Right")],
                            "help_text": "This indicates the position of the image in the desktop view.",
                            "label": "Image Position",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("description", 2),
                                ("hr", 3),
                                ("featured_image", 4),
                                ("image_position", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.StructBlock", [[("title", 1)]], {}),
                    8: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text_block", 0), ("banner_block", 6), ("test_block", 7)]],
                        {"required": False},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
    ]
