# Generated by Django 5.2.1 on 2025-07-07 18:33

from django.db import migrations, models

import baseapp_reactions.models
import baseapp_reports.models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_standardpage_comments_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardpage",
            name="is_reactions_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="reactions_count",
            field=models.JSONField(
                default=baseapp_reactions.models.default_reactions_count, editable=False
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="reports_count",
            field=models.JSONField(default=baseapp_reports.models.default_reports_count),
        ),
    ]
