# Generated by Django 5.1.11 on 2025-07-15 20:18

from django.db import migrations

import baseapp_wagtail.base.stream_fields.featured_image_stream_field


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_standardpage_is_reactions_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="featured_image",
            field=baseapp_wagtail.base.stream_fields.featured_image_stream_field.FeaturedImageStreamField(
                [("featured_image", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'If this is a <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">decorative image</a>, please leave this field blank.',
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("image", 0), ("alt_text", 1)]], {}),
                },
                null=True,
                verbose_name="Featured Image",
            ),
        ),
    ]
