# Generated by Django 5.1.11 on 2025-08-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_standardpage_featured_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardpage",
            name="is_reactions_enabled",
        ),
        migrations.RemoveField(
            model_name="standardpage",
            name="reactions_count",
        ),
        migrations.RemoveField(
            model_name="standardpage",
            name="reports_count",
        ),
    ]
