# Generated by Django 5.0.1 on 2025-01-07 20:46

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0006_remove_messagestatus_increment_unread_count_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="increment_unread_count",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NOT NEW."is_read")',
                    func="\n            INSERT INTO baseapp_chats_unreadmessagecount (room_id, profile_id, marked_unread, count)\n            VALUES ((SELECT room_id FROM baseapp_chats_message WHERE id = NEW.message_id), NEW.profile_id, False, 1)\n            ON CONFLICT (room_id, profile_id)\n            DO UPDATE SET count = baseapp_chats_unreadmessagecount.count + 1;\n            RETURN NULL;\n        ",
                    hash="e18409b9d00a1d881dabf9b7aaa8da101ac5ac28",
                    operation="INSERT",
                    pgid="pgtrigger_increment_unread_count_ec3cd",
                    table="baseapp_chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
    ]
