# Generated by Django 5.2.3 on 2025-08-13 14:36

import django.db.models.deletion
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0008_alter_chatroomparticipant_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="messagestatus",
            name="increment_unread_count",
        ),
        migrations.AddField(
            model_name="message",
            name="content_linked_profile_actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_as_content_actor_set",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="content_linked_profile_target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_as_content_target_set",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.IntegerField(
                choices=[(1, "User message"), (2, "System message")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
