# Generated by Django 5.1.11 on 2025-09-11 18:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0010_message_deleted"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="chatroom",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'chatroom')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="e26ea2fc30298b7b709e89092e096bda4297c23f",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_55bc4",
                    table="baseapp_chats_chatroom",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroomparticipant",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'chatroomparticipant')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="7a2e21728232c5a9a5329b6a9a7bf587d8f62492",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_9115c",
                    table="baseapp_chats_chatroomparticipant",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'message')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="6aaa19a949462493cd684755c15a38721f502aac",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_13d45",
                    table="baseapp_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'messagestatus')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="478267f148fb24f62dae04b0320a891e56cfeda1",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_38b03",
                    table="baseapp_chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="unreadmessagecount",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'unreadmessagecount')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="3ad75868570c3f4ac56720041a4ed3ec7f9360d8",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_20437",
                    table="baseapp_chats_unreadmessagecount",
                    when="AFTER",
                ),
            ),
        ),
    ]
