# Generated by Django 5.2.9 on 2025-12-18 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0011_alter_chatroom_created_by_and_more"),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="created_by_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_created_rooms",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
            ),
        ),
    ]
