# Generated by Django 5.1.11 on 2025-08-27 14:04

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0012_remove_message_create_message_status_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="create_message_status",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."message_type" = 1)',
                    func="\n            INSERT INTO baseapp_chats_messagestatus (message_id, profile_id, is_read)\n            SELECT NEW.id, crp.profile_id, CASE WHEN NEW.profile_id = crp.profile_id THEN TRUE ELSE FALSE END\n            FROM baseapp_chats_chatroomparticipant as crp\n            WHERE crp.room_id = NEW.room_id;\n            RETURN NULL;\n        ",
                    hash="beb46ab0586aff0156230e06f0f378f3af30b54b",
                    operation="INSERT",
                    pgid="pgtrigger_create_message_status_c941b",
                    table="baseapp_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="increment_unread_count",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NOT NEW."is_read")',
                    func="\n            INSERT INTO baseapp_chats_unreadmessagecount (room_id, profile_id, marked_unread, count)\n            VALUES ((SELECT room_id FROM baseapp_chats_message WHERE id = NEW.message_id), NEW.profile_id, False, 1)\n            ON CONFLICT (room_id, profile_id)\n            DO UPDATE SET count = baseapp_chats_unreadmessagecount.count + 1;\n            RETURN NULL;\n        ",
                    hash="e18409b9d00a1d881dabf9b7aaa8da101ac5ac28",
                    operation="INSERT",
                    pgid="pgtrigger_increment_unread_count_ec3cd",
                    table="baseapp_chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
    ]
