# Generated by Django 5.1.15 on 2025-12-24 14:22

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0012_chatroom_created_by_profile"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="chatroom",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'chatroom'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="6e537c25000376cc3d84d1fc7342e29daefcc7b5",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_47791",
                    table="baseapp_chats_chatroom",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroom",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'chatroom')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="0d086570763759bf6aa558967a33fc7d6b42921a",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_4ef10",
                    table="baseapp_chats_chatroom",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroomparticipant",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'chatroomparticipant'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="2c927ab8aefbf29f776a8787e3e9ad50db1ed81b",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_14cd3",
                    table="baseapp_chats_chatroomparticipant",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroomparticipant",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'chatroomparticipant')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="f7c87a936b38f449aa15233cd1b71efd3915b890",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_5fb69",
                    table="baseapp_chats_chatroomparticipant",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'message'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="30af169e05dfbf2bde63237a9226604fe37a82c0",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_45262",
                    table="baseapp_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'message')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="f1b179b964dbdffd55b81d3bf8d79d451e25d913",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_f1512",
                    table="baseapp_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'messagestatus'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="91c67a9b0a41dd7a39bb92465e05c5a5121405c3",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_96500",
                    table="baseapp_chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'messagestatus')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="5515a153c8b983528f372039b96a617892486233",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_c16f0",
                    table="baseapp_chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="unreadmessagecount",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'unreadmessagecount'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="f9223941a338852382d3288765c122625b1dcf57",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_12d5b",
                    table="baseapp_chats_unreadmessagecount",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="unreadmessagecount",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_chats' AND model = 'unreadmessagecount')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="57e8daf7ebc9483ae8409f2d33f61e346b9af6d6",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_0dcf6",
                    table="baseapp_chats_unreadmessagecount",
                    when="AFTER",
                ),
            ),
        ),
    ]
