# Generated by Django 5.2.3 on 2025-11-12 16:03

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0012_chatroom_insert_public_id_mapping_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroom",
            name="insert_public_id_mapping",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroom",
            name="delete_public_id_mapping",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroomparticipant",
            name="insert_public_id_mapping",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroomparticipant",
            name="delete_public_id_mapping",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="message",
            name="create_message_status",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="messagestatus",
            name="increment_unread_count",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="unreadmessagecount",
            name="insert_public_id_mapping",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="unreadmessagecount",
            name="delete_public_id_mapping",
        ),
    ]
