# Generated by Django 5.2.12 on 2026-04-27 20:29

import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0013_chatroom_insert_document_id_and_more"),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroom",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroom",
            name="delete_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroomparticipant",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroomparticipant",
            name="delete_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="message",
            name="create_message_status",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="message",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="message",
            name="delete_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="messagestatus",
            name="increment_unread_count",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="messagestatus",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="messagestatus",
            name="delete_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="unreadmessagecount",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="unreadmessagecount",
            name="delete_document_id",
        ),
        migrations.AddField(
            model_name="message",
            name="mentioned_profiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_mentions",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                verbose_name="mentioned profiles",
            ),
        ),
    ]
