# Generated by Django 5.2.12 on 2026-03-20 16:35

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0013_chatroom_insert_document_id_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroom",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroom",
            name="delete_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroomparticipant",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="chatroomparticipant",
            name="delete_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="message",
            name="create_message_status",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="message",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="message",
            name="delete_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="messagestatus",
            name="increment_unread_count",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="messagestatus",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="messagestatus",
            name="delete_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="unreadmessagecount",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="unreadmessagecount",
            name="delete_document_id",
        ),
    ]
