# Generated by Django 5.2.12 on 2026-03-23 15:15

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_chats", "0014_remove_chatroom_insert_document_id_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="message",
            name="create_message_status",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="messagestatus",
            name="increment_unread_count",
        ),
    ]
