# Generated by Django 5.0.1 on 2024-06-07 21:35

from django.db import migrations, models

import baseapp_comments.models
import baseapp_reports.models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blockers_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="blocking_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="comments_count",
            field=models.JSONField(
                default=baseapp_comments.models.default_comments_count,
                editable=False,
                verbose_name="comments count",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="followers_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="following_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_comments_enabled",
            field=models.BooleanField(default=True, verbose_name="is comments enabled"),
        ),
        migrations.AddField(
            model_name="profile",
            name="reports_count",
            field=models.JSONField(default=baseapp_reports.models.default_reports_count),
        ),
    ]
