# Generated by Django 5.0.11 on 2025-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_profiles", "0005_profileuserrole_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True, verbose_name="name"
            ),
        ),
    ]
