# Generated by Django 5.0.11 on 2025-03-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_profiles", "0005_profileuserrole_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
    ]
