# Generated by Django 5.1.4 on 2024-12-16 18:04

from django.db import migrations

CREATE_SQL = """
create or replace view v_activity_log as select
    pc.id as id,
    pc.created_at as created_at,
    pc.updated_at as updated_at,
    nullif(metadata->>'user', '')::int8 as user_id,
    nullif(metadata->>'profile', '')::int8 as profile_id,
    metadata->>'url' as url,
    metadata->>'verb' as verb,
    nullif(metadata->>'visibility', '')::int4 as visibility,
    metadata->>'ip_address' as ip_address,
    metadata
from pghistory_context pc
"""

DROP_SQL = "drop view if exists v_activity_log"


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_activity_log", "0001_initial"),
    ]

    operations = [migrations.RunSQL(sql=CREATE_SQL, reverse_sql=DROP_SQL)]
