# Generated by Django 5.1.15 on 2026-04-01 20:24

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="organization",
            trigger=pgtrigger.compiler.Trigger(
                name="update_profile_name",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            IF NEW.profile_id IS NOT NULL THEN\n                UPDATE profiles_profile SET name = TRIM(NEW.name) WHERE id = NEW.profile_id;\n            END IF;\n            RETURN NULL;\n        ",
                    hash="0c9442fe3c02cbf4257d1755907d996256af3f5c",
                    operation="UPDATE",
                    pgid="pgtrigger_update_profile_name_82ccf",
                    table="organizations_organization",
                    when="AFTER",
                ),
            ),
        ),
    ]
