# Generated by Django 5.2.12 on 2026-04-21 19:06

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="organization",
            trigger=pgtrigger.compiler.Trigger(
                name="update_profile_name",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            IF NEW.profile_id IS NOT NULL THEN\n                UPDATE profiles_profile SET name = TRIM(COALESCE(NEW.name, '')) WHERE id = NEW.profile_id;\n            END IF;\n            RETURN NULL;\n        ",
                    hash="81b97828dae155f84e53e2f66238f9dc414e2c24",
                    operation='UPDATE OF "name"',
                    pgid="pgtrigger_update_profile_name_82ccf",
                    table="organizations_organization",
                    when="AFTER",
                ),
            ),
        ),
    ]
