# Generated by Django 5.2.12 on 2026-04-06 20:48

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_update_profile_name"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="organization",
            name="update_profile_name",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="organization",
            trigger=pgtrigger.compiler.Trigger(
                name="update_profile_name",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            IF NEW.profile_id IS NOT NULL THEN\n                UPDATE profiles_profile SET name = TRIM(NEW.name) WHERE id = NEW.profile_id;\n            END IF;\n            RETURN NULL;\n        ",
                    hash="a4f79d20fe54c9bef16845dfbe30c6339e92811d",
                    operation='UPDATE OF "name"',
                    pgid="pgtrigger_update_profile_name_82ccf",
                    table="organizations_organization",
                    when="AFTER",
                ),
            ),
        ),
    ]
