# Generated by Django 5.0.9 on 2024-09-19 00:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import baseapp_wagtail.models
import baseapp_wagtail.stream_fields.page_body_stream_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "featured_image",
                    wagtail.fields.StreamField(
                        [("featured_image", 2)],
                        block_lookup={
                            0: (
                                "baseapp_wagtail.blocks.basic_blocks.custom_image_chooser_block.block.CustomImageChooserBlock",
                                (),
                                {"image_sizes": None, "required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": 'If this is a <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">decorative image</a>, please leave this field blank.',
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 0), ("alt_text", 1)]],
                                {},
                            ),
                        },
                        null=True,
                        verbose_name="Featured Image",
                    ),
                ),
                (
                    "body",
                    baseapp_wagtail.stream_fields.page_body_stream_field.PageBodyStreamField(
                        [("section_stream_block", 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                "baseapp_wagtail.blocks.basic_blocks.custom_rich_text_block.block.CustomRichTextBlock",
                                (),
                                {"icon": "pilcrow", "template": "base/blocks/rich_text_block.html"},
                            ),
                            1: (
                                "wagtail.blocks.StreamBlock",
                                [[("rich_text_block", 0)]],
                                {"required": False},
                            ),
                        },
                        verbose_name="Page body",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard page",
                "verbose_name_plural": "Standard pages",
            },
            bases=(baseapp_wagtail.models.HeadlessPageMixin, "wagtailcore.page"),
        ),
    ]
