# Generated by Django 5.0.1 on 2024-02-07 14:25

from django.db import migrations

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_superuserupdatelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
