# Generated by Django 5.1.15 on 2026-01-07 18:06

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import baseapp_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=baseapp_core.models.random_name_in("chat_room_images"),
                        verbose_name="image",
                    ),
                ),
                (
                    "last_message_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ("participants_count", models.IntegerField(default=0)),
                ("messages_count", models.IntegerField(default=0)),
                ("is_group", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_created_rooms",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_time", "-created"],
                "abstract": False,
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ChatRoomParticipant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("role", models.IntegerField(choices=[(1, "member"), (2, "admin")], default=1)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("has_archived_room", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to=settings.BASEAPP_CHATS_CHATROOM_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-role", "profile__name"],
                "abstract": False,
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "message_type",
                    models.IntegerField(
                        choices=[(1, "User message"), (2, "System message")], default=1
                    ),
                ),
                (
                    "verb",
                    models.IntegerField(
                        choices=[(100, "sent a message")], db_index=True, default=100
                    ),
                ),
                (
                    "action_object_object_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("extra_data", models.JSONField(blank=True, null=True)),
                (
                    "action_object_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_object",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "content_linked_profile_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_as_content_actor_set",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
                (
                    "content_linked_profile_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_as_content_target_set",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
                (
                    "in_reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to=settings.BASEAPP_CHATS_MESSAGE_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.BASEAPP_CHATS_CHATROOM_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.BASEAPP_CHATS_MESSAGE_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MessageStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to=settings.BASEAPP_CHATS_MESSAGE_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        migrations.CreateModel(
            name="UnreadMessageCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("marked_unread", models.BooleanField(default=False)),
                ("count", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unread_messages",
                        to=settings.BASEAPP_CHATS_CHATROOM_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroomparticipant",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'chats' AND model = 'chatroomparticipant'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="1ca089b424542cf507cdec1025760dd193e0bd1f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_75ff5",
                    table="chats_chatroomparticipant",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroomparticipant",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'chats' AND model = 'chatroomparticipant')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="5a31df75ad41ccd58ba68bcbbc2a8d1dba59aea0",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_85cf3",
                    table="chats_chatroomparticipant",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="set_last_message",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            UPDATE chats_chatroom\n            SET last_message_id = NEW.id, last_message_time = NEW.created\n            WHERE id = NEW.room_id;\n            RETURN NULL;\n        ",
                    hash="0ae837946cb67f108de377907bd057ae23dff10a",
                    operation="INSERT",
                    pgid="pgtrigger_set_last_message_7f915",
                    table="chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="create_message_status",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."message_type" = 1)',
                    func="\n            INSERT INTO chats_messagestatus (message_id, profile_id, is_read)\n            SELECT NEW.id, crp.profile_id, CASE WHEN NEW.profile_id = crp.profile_id THEN TRUE ELSE FALSE END\n            FROM chats_chatroomparticipant as crp\n            WHERE crp.room_id = NEW.room_id;\n            RETURN NULL;\n        ",
                    hash="cbf349f0d09f94d02e2135628f1f96fbbe32e3fe",
                    operation="INSERT",
                    pgid="pgtrigger_create_message_status_ef343",
                    table="chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="update_last_message",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            UPDATE chats_chatroom\n            SET last_message_id = (\n                SELECT id\n                FROM chats_message\n                WHERE room_id = OLD.room_id\n                ORDER BY created DESC\n                LIMIT 1\n            ),\n            last_message_time = (\n                SELECT created\n                FROM chats_message\n                WHERE room_id = OLD.room_id\n                ORDER BY created DESC\n                LIMIT 1\n            )\n            WHERE id = OLD.room_id;\n            RETURN NULL;\n        ",
                    hash="08afc20839b9d6b06dcf809b80d72d6dfeb5936b",
                    operation="DELETE",
                    pgid="pgtrigger_update_last_message_af92a",
                    table="chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'chats' AND model = 'message'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="f18908ebea702b8f7ff10128318831aa7a2faf59",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_904e0",
                    table="chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'chats' AND model = 'message')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="32cd776cbd547fd3e2c8eef4d69471fadae1a9fb",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_7b06c",
                    table="chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroom",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'chats' AND model = 'chatroom'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="bbf36f990c900f6a2ef099d19f3286d90d4429c8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_0b62d",
                    table="chats_chatroom",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroom",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'chats' AND model = 'chatroom')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="4cbda3205541680e7651d7d5f6daaf572e993cf7",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_3bf75",
                    table="chats_chatroom",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagestatus",
            unique_together={("message_id", "profile_id")},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="increment_unread_count",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NOT NEW."is_read")',
                    func="\n            INSERT INTO chats_unreadmessagecount (room_id, profile_id, marked_unread, count)\n            VALUES ((SELECT room_id FROM chats_message WHERE id = NEW.message_id), NEW.profile_id, False, 1)\n            ON CONFLICT (room_id, profile_id)\n            DO UPDATE SET count = chats_unreadmessagecount.count + 1;\n            RETURN NULL;\n        ",
                    hash="6ef726e280bb2701eeada44131b85bcf93fd5ebe",
                    operation="INSERT",
                    pgid="pgtrigger_increment_unread_count_61748",
                    table="chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="decrement_unread_count",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."is_read" AND NOT OLD."is_read")',
                    func="\n            UPDATE chats_unreadmessagecount\n            SET count = GREATEST(0, count - 1)\n            WHERE\n                room_id = (SELECT room_id FROM chats_message WHERE id = NEW.message_id) AND\n                profile_id = NEW.profile_id;\n            RETURN NULL;\n        ",
                    hash="958fcc7ada69f451f0f84c13ae4335e0eaff4cbe",
                    operation="UPDATE",
                    pgid="pgtrigger_decrement_unread_count_f1baa",
                    table="chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'chats' AND model = 'messagestatus'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="d94710bac4feb65f9a1c1fdeed7766b11cd75232",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_5f1ce",
                    table="chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'chats' AND model = 'messagestatus')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="833816f3b8b50250379a716745137571ff64f551",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_ae1ee",
                    table="chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unreadmessagecount",
            unique_together={("room_id", "profile_id")},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="unreadmessagecount",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'chats' AND model = 'unreadmessagecount'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="83e58b9a0b8ea41b8a1ccea9097ddf8a4071e929",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_515f8",
                    table="chats_unreadmessagecount",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="unreadmessagecount",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'chats' AND model = 'unreadmessagecount')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="696530d3e4d1683361cb05ddd2786fcbe322fc08",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_bdb7f",
                    table="chats_unreadmessagecount",
                    when="AFTER",
                ),
            ),
        ),
    ]
