# Generated by Django 5.1.11 on 2025-09-15 14:28

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_ratings", "0003_rate_profile"),
        ("baseapp_core", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="rate",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_publicidmapping (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_ratings' AND model = 'rate'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="8b00171eaa0632287bd531fa0b68e5345c68a909",
                    operation="INSERT",
                    pgid="pgtrigger_insert_public_id_mapping_adba8",
                    table="baseapp_ratings_rate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="rate",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_ratings' AND model = 'rate')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="6a080acd1e394b87d259784731250a42484ae4bf",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_878ee",
                    table="baseapp_ratings_rate",
                    when="AFTER",
                ),
            ),
        ),
    ]
