# Generated by Django 5.1.14 on 2025-12-03 04:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_ratings", "0003_rate_profile"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="rate",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_ratings' AND model = 'rate'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="e04c9d609885002fbf23b8a3794522fabd828ff1",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_16c1a",
                    table="baseapp_ratings_rate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="rate",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_ratings' AND model = 'rate')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="5f8b6574e6c18885743dcf73b94863155de0048f",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_96026",
                    table="baseapp_ratings_rate",
                    when="AFTER",
                ),
            ),
        ),
    ]
