# Generated by Django 5.1.13 on 2025-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_wagtail_medias", "0002_customimage_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdocument",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customrendition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
