# Generated by Django 5.2.3 on 2025-10-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_wagtail_medias", "0003_alter_customdocument_id_alter_customimage_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdocument",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customrendition",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
