# Generated by Django 5.0.1 on 2024-06-21 01:47

import django.db.models.deletion
import swapper
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_blocks", "0002_block_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        swapper.dependency("baseapp_profiles", "Profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocking",
                to=swapper.get_model_name("baseapp_profiles", "Profile"),
                verbose_name="blocking",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blockers",
                to=swapper.get_model_name("baseapp_profiles", "Profile"),
                verbose_name="blockers",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
