# Generated by Django 5.0.11 on 2025-04-07 20:16

import swapper
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_reactions", "0003_reaction_profile"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        swapper.dependency("baseapp_profiles", "Profile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("profile", "target_content_type", "target_object_id")},
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="baseapp_rea_target__9e25dd_idx",
            ),
        ),
    ]
