# Generated by Django 5.1.15 on 2025-12-24 14:29

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import baseapp_core.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_name_alter_profileevent_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileUserRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("role", models.IntegerField(choices=[(1, "admin"), (2, "manager")], default=2)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "active"), (2, "pending"), (3, "inactive")], default=2
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'profiles' AND model = 'profile'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="1737ac4db9254b3bcd1ad8f3061288d0d6d92848",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_f806f",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'profiles' AND model = 'profile')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="d319f86e1e122c559c74ae444ea983313e81303b",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_91033",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="profileuserrole",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                verbose_name="profile",
            ),
        ),
        migrations.AddField(
            model_name="profileuserrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="profileuserrole",
            unique_together={("user", "profile")},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profileuserrole",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'profiles' AND model = 'profileuserrole'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="90414fa46712472d9e061da6f2c1d53e723e106e",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_3bbc3",
                    table="profiles_profileuserrole",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profileuserrole",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'profiles' AND model = 'profileuserrole')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="c0012b04441ab74dbeaae16a73c6377f0a22366e",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_5ec40",
                    table="profiles_profileuserrole",
                    when="AFTER",
                ),
            ),
        ),
    ]
