# Generated by Django 5.1.14 on 2025-12-03 04:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_name_alter_profileevent_name"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'profiles' AND model = 'profile'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="1737ac4db9254b3bcd1ad8f3061288d0d6d92848",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_f806f",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'profiles' AND model = 'profile')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="d319f86e1e122c559c74ae444ea983313e81303b",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_91033",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
    ]
