# Generated by Django 5.1.11 on 2025-09-11 18:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_name_alter_profileevent_name"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'profiles' AND model = 'profile')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="9f1c55024a42fea1ddafceaebd246d9f2a5ac6d7",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_da649",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
    ]
