# Generated by Django 5.1.13 on 2025-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_name_alter_profileevent_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profileevent",
            name="id",
            field=models.BigIntegerField(),
        ),
    ]
