# Generated by Django 5.1.15 on 2026-02-04 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profileuserrole_profile_insert_document_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuserrole",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="profileuserrole",
            name="status",
            field=models.IntegerField(
                choices=[(1, "active"), (2, "pending"), (3, "inactive")], default=3
            ),
        ),
        migrations.AlterField(
            model_name="profileuserrole",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
