# Generated by Django 5.1.15 on 2026-03-12 19:05

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("profiles", "0003_profileuserrole_profile_insert_document_id_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="delete_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profileuserrole",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profileuserrole",
            name="delete_document_id",
        ),
        migrations.AlterUniqueTogether(
            name="profile",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="target_content_type",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="target_object_id",
        ),
        migrations.AddField(
            model_name="profile",
            name="target",
            field=models.ForeignKey(
                blank=True,
                help_text="The object that this profile is associated with. The object is identified by its DocumentId.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="baseapp_core.documentid",
                verbose_name="target object",
            ),
        ),
        migrations.AddField(
            model_name="profileevent",
            name="target",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The object that this profile is associated with. The object is identified by its DocumentId.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="baseapp_core.documentid",
                verbose_name="target object",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "comments_count", "created", "followers_count", "following_count", "id", "image", "is_comments_enabled", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reports_count", "status", "target_id") VALUES (NEW."banner_image", NEW."biography", NEW."blockers_count", NEW."blocking_count", NEW."comments_count", NEW."created", NEW."followers_count", NEW."following_count", NEW."id", NEW."image", NEW."is_comments_enabled", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reports_count", NEW."status", NEW."target_id"); RETURN NULL;',
                    hash="5cbd53103353d3f2ab54760618d4562d61631db4",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_87e8d",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "comments_count", "created", "followers_count", "following_count", "id", "image", "is_comments_enabled", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reports_count", "status", "target_id") VALUES (NEW."banner_image", NEW."biography", NEW."blockers_count", NEW."blocking_count", NEW."comments_count", NEW."created", NEW."followers_count", NEW."following_count", NEW."id", NEW."image", NEW."is_comments_enabled", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reports_count", NEW."status", NEW."target_id"); RETURN NULL;',
                    hash="66aa873c605401533fc7e85a98b94e0209aa25ee",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c0aea",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "comments_count", "created", "followers_count", "following_count", "id", "image", "is_comments_enabled", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reports_count", "status", "target_id") VALUES (OLD."banner_image", OLD."biography", OLD."blockers_count", OLD."blocking_count", OLD."comments_count", OLD."created", OLD."followers_count", OLD."following_count", OLD."id", OLD."image", OLD."is_comments_enabled", OLD."modified", OLD."name", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reports_count", OLD."status", OLD."target_id"); RETURN NULL;',
                    hash="0f036219f14e233376ce62d4b5a69426f1578a5b",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_4fa3e",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="target_content_type",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="target_object_id",
        ),
    ]
