# Generated by Django 5.2.14 on 2026-06-08 13:11

import pgtrigger.compiler
import pgtrigger.migrations
from django.apps import apps as django_apps
from django.db import migrations

from baseapp_blocks.migration_helpers.convert_legacy_block_counts_to_metadata_helper import (
    migrate_legacy_block_counts_to_metadata,
    reverse_migrate_legacy_block_counts_from_metadata,
)
from baseapp_comments.migration_helpers.convert_legacy_commentable_fields_into_metadata_helper import (
    migrate_legacy_commentable_fields_to_metadata,
    reverse_migrate_legacy_commentable_fields_from_metadata,
)


def migrate_profile_commentable_fields(apps, schema_editor):
    migrate_legacy_commentable_fields_to_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
    )


def reverse_migrate_profile_commentable_fields(apps, schema_editor):
    reverse_migrate_legacy_commentable_fields_from_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
    )


def migrate_profile_reports_count(apps, schema_editor):
    # ReportableMetadata only exists when baseapp_reports is installed; skip the
    # backfill otherwise. The column removal / trigger regen below run regardless.
    try:
        apps.get_model("reports", "ReportableMetadata")
    except LookupError:
        return

    from baseapp_reports.migration_helpers.convert_legacy_reports_count_to_metadata_helper import (
        migrate_legacy_reports_count_to_metadata,
    )

    migrate_legacy_reports_count_to_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
        metadata_app_label="reports",
    )


def reverse_migrate_profile_reports_count(apps, schema_editor):
    try:
        apps.get_model("reports", "ReportableMetadata")
    except LookupError:
        return

    from baseapp_reports.migration_helpers.convert_legacy_reports_count_to_metadata_helper import (
        reverse_migrate_legacy_reports_count_from_metadata,
    )

    reverse_migrate_legacy_reports_count_from_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
        metadata_app_label="reports",
    )


def migrate_profile_block_counts(apps, schema_editor):
    migrate_legacy_block_counts_to_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
        metadata_app_label="blocks",
    )


def reverse_migrate_profile_block_counts(apps, schema_editor):
    reverse_migrate_legacy_block_counts_from_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
        metadata_app_label="blocks",
    )


def _dependencies():
    # reports is optional (app-disable support); depend on it only when installed.
    deps = [
        ("blocks", "0002_blockablemetadata"),
        ("comments", "0002_commentablemetadata"),
        ("profiles", "0004_remove_profile_insert_insert_and_more"),
    ]
    if "reports" in django_apps.app_configs:
        deps.append(("reports", "0002_reportablemetadata"))
    return deps


class Migration(migrations.Migration):

    replaces = [
        ("profiles", "0005_remove_profile_insert_insert_and_more"),
        ("profiles", "0006_remove_reports_count"),
        ("profiles", "0007_remove_profile_insert_insert_and_more"),
    ]

    dependencies = _dependencies()

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="delete_delete",
        ),
        migrations.RunPython(
            code=migrate_profile_commentable_fields,
            reverse_code=reverse_migrate_profile_commentable_fields,
        ),
        migrations.RemoveField(
            model_name="profile",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_comments_enabled",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="is_comments_enabled",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reports_count", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."blockers_count", NEW."blocking_count", NEW."created", NEW."id", NEW."image", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reports_count", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="6bd47c75381f6feb8ff5a0cdd6fd96bb921ca6f7",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_87e8d",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reports_count", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."blockers_count", NEW."blocking_count", NEW."created", NEW."id", NEW."image", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reports_count", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="b2a7e175a2927b1eab29c5811fe9818702f05bfc",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c0aea",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reports_count", "status", "target_content_type_id", "target_object_id") VALUES (OLD."banner_image", OLD."biography", OLD."blockers_count", OLD."blocking_count", OLD."created", OLD."id", OLD."image", OLD."modified", OLD."name", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reports_count", OLD."status", OLD."target_content_type_id", OLD."target_object_id"); RETURN NULL;',
                    hash="d135c72529015e58ab68feef8ba4293e283f3450",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_4fa3e",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="delete_delete",
        ),
        migrations.RunPython(
            code=migrate_profile_reports_count,
            reverse_code=reverse_migrate_profile_reports_count,
        ),
        migrations.RemoveField(
            model_name="profile",
            name="reports_count",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="reports_count",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."blockers_count", NEW."blocking_count", NEW."created", NEW."id", NEW."image", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="19ff46009267a41eea52eece4d6982a26fbe5221",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_87e8d",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."blockers_count", NEW."blocking_count", NEW."created", NEW."id", NEW."image", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="cd037b7a5e517dc59b2a53026be442e7b46bffb1",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c0aea",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (OLD."banner_image", OLD."biography", OLD."blockers_count", OLD."blocking_count", OLD."created", OLD."id", OLD."image", OLD."modified", OLD."name", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."target_content_type_id", OLD."target_object_id"); RETURN NULL;',
                    hash="678d32b38297565e01cbd33586a3dfd87fdc8440",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_4fa3e",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="delete_delete",
        ),
        migrations.RunPython(
            code=migrate_profile_block_counts,
            reverse_code=reverse_migrate_profile_block_counts,
        ),
        migrations.RemoveField(
            model_name="profile",
            name="blockers_count",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="blocking_count",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="blockers_count",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="blocking_count",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="created",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="modified",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "id", "image", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."id", NEW."image", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="280857d24a1adce126dedf5e6e4277354aacc4aa",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_87e8d",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."banner_image" IS DISTINCT FROM (NEW."banner_image") OR OLD."biography" IS DISTINCT FROM (NEW."biography") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."image" IS DISTINCT FROM (NEW."image") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."target_content_type_id" IS DISTINCT FROM (NEW."target_content_type_id") OR OLD."target_object_id" IS DISTINCT FROM (NEW."target_object_id"))',
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "id", "image", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."id", NEW."image", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="df274f1ff855d95fd42a000bee562cbb6e70fda7",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c0aea",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "id", "image", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (OLD."banner_image", OLD."biography", OLD."id", OLD."image", OLD."name", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."target_content_type_id", OLD."target_object_id"); RETURN NULL;',
                    hash="a569f1f00728f92558a592f7ce4e74da88509491",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_4fa3e",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
    ]
