# Generated by Django 5.2.12 on 2026-04-22 19:14

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations

from baseapp_comments.migration_helpers.convert_legacy_commentable_fields_into_metadata_helper import (
    migrate_legacy_commentable_fields_to_metadata,
    reverse_migrate_legacy_commentable_fields_from_metadata,
)


def migrate_profile_commentable_fields(apps, schema_editor):
    migrate_legacy_commentable_fields_to_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
    )


def reverse_migrate_profile_commentable_fields(apps, schema_editor):
    reverse_migrate_legacy_commentable_fields_from_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_remove_profile_insert_insert_and_more"),
        ("comments", "0002_commentablemetadata"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="delete_delete",
        ),
        migrations.RunPython(
            migrate_profile_commentable_fields,
            reverse_migrate_profile_commentable_fields,
        ),
        migrations.RemoveField(
            model_name="profile",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_comments_enabled",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="is_comments_enabled",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reports_count", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."blockers_count", NEW."blocking_count", NEW."created", NEW."id", NEW."image", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reports_count", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="6bd47c75381f6feb8ff5a0cdd6fd96bb921ca6f7",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_87e8d",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reports_count", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."blockers_count", NEW."blocking_count", NEW."created", NEW."id", NEW."image", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reports_count", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="b2a7e175a2927b1eab29c5811fe9818702f05bfc",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c0aea",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reports_count", "status", "target_content_type_id", "target_object_id") VALUES (OLD."banner_image", OLD."biography", OLD."blockers_count", OLD."blocking_count", OLD."created", OLD."id", OLD."image", OLD."modified", OLD."name", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reports_count", OLD."status", OLD."target_content_type_id", OLD."target_object_id"); RETURN NULL;',
                    hash="d135c72529015e58ab68feef8ba4293e283f3450",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_4fa3e",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
    ]
