# Generated by Django 5.1.15 on 2026-02-10 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_add_email_to_profileuserrole"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuserrole",
            name="invitation_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the invitation expires",
                null=True,
                verbose_name="invitation expires at",
            ),
        ),
        migrations.AddField(
            model_name="profileuserrole",
            name="invitation_token",
            field=models.CharField(
                blank=True,
                help_text="Unique token for accepting invitation",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="invitation token",
            ),
        ),
        migrations.AddField(
            model_name="profileuserrole",
            name="invited_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the invitation was sent",
                null=True,
                verbose_name="invited at",
            ),
        ),
        migrations.AddField(
            model_name="profileuserrole",
            name="invited_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address invitation was sent to (for pending invitations)",
                max_length=254,
                null=True,
                verbose_name="invited email",
            ),
        ),
        migrations.AddField(
            model_name="profileuserrole",
            name="responded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user accepted or declined",
                null=True,
                verbose_name="responded at",
            ),
        ),
        migrations.AlterField(
            model_name="profileuserrole",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "active"),
                    (2, "pending"),
                    (3, "inactive"),
                    (4, "declined"),
                    (5, "expired"),
                ],
                default=3,
            ),
        ),
        migrations.AddConstraint(
            model_name="profileuserrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invited_email__isnull", False)),
                fields=("profile", "invited_email"),
                name="unique_profile_invited_email",
            ),
        ),
    ]
