# Generated by Django 5.2.12 on 2026-05-07 15:40

import pgtrigger.compiler
import pgtrigger.migrations
from django.apps import apps as django_apps
from django.db import migrations


def migrate_profile_reports_count(apps, schema_editor):
    # ReportableMetadata only exists when baseapp_reports is installed; skip the
    # backfill otherwise. The column removal / trigger regen below run regardless.
    try:
        apps.get_model("reports", "ReportableMetadata")
    except LookupError:
        return

    from baseapp_reports.migration_helpers.convert_legacy_reports_count_to_metadata_helper import (
        migrate_legacy_reports_count_to_metadata,
    )

    migrate_legacy_reports_count_to_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
        metadata_app_label="reports",
    )


def reverse_migrate_profile_reports_count(apps, schema_editor):
    try:
        apps.get_model("reports", "ReportableMetadata")
    except LookupError:
        return

    from baseapp_reports.migration_helpers.convert_legacy_reports_count_to_metadata_helper import (
        reverse_migrate_legacy_reports_count_from_metadata,
    )

    reverse_migrate_legacy_reports_count_from_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
        metadata_app_label="reports",
    )


def _dependencies():
    dependencies = [
        ("profiles", "0005_remove_profile_insert_insert_and_more"),
    ]
    if "reports" in django_apps.app_configs:
        dependencies.append(("reports", "0002_reportablemetadata"))
    return dependencies


class Migration(migrations.Migration):

    dependencies = _dependencies()

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="delete_delete",
        ),
        migrations.RunPython(
            migrate_profile_reports_count,
            reverse_migrate_profile_reports_count,
        ),
        migrations.RemoveField(
            model_name="profile",
            name="reports_count",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="reports_count",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."blockers_count", NEW."blocking_count", NEW."created", NEW."id", NEW."image", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="19ff46009267a41eea52eece4d6982a26fbe5221",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_87e8d",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."blockers_count", NEW."blocking_count", NEW."created", NEW."id", NEW."image", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="cd037b7a5e517dc59b2a53026be442e7b46bffb1",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c0aea",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "blockers_count", "blocking_count", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (OLD."banner_image", OLD."biography", OLD."blockers_count", OLD."blocking_count", OLD."created", OLD."id", OLD."image", OLD."modified", OLD."name", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."target_content_type_id", OLD."target_object_id"); RETURN NULL;',
                    hash="678d32b38297565e01cbd33586a3dfd87fdc8440",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_4fa3e",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
    ]
