# Generated by Django 5.1.15 on 2026-02-11 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_add_invitation_delivery_tracking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileuserrole",
            name="invitation_last_send_provider_message_id",
        ),
    ]
