# Generated by Django 5.2.14 on 2026-05-19 12:25

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations

from baseapp_blocks.migration_helpers.convert_legacy_block_counts_to_metadata_helper import (
    migrate_legacy_block_counts_to_metadata,
    reverse_migrate_legacy_block_counts_from_metadata,
)


def migrate_profile_block_counts(apps, schema_editor):
    migrate_legacy_block_counts_to_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
        metadata_app_label="blocks",
    )


def reverse_migrate_profile_block_counts(apps, schema_editor):
    reverse_migrate_legacy_block_counts_from_metadata(
        apps,
        schema_editor,
        source_app_label="profiles",
        source_model_name="Profile",
        metadata_app_label="blocks",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_remove_reports_count"),
        ("blocks", "0002_blockablemetadata"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="delete_delete",
        ),
        migrations.RunPython(
            migrate_profile_block_counts,
            reverse_migrate_profile_block_counts,
        ),
        migrations.RemoveField(
            model_name="profile",
            name="blockers_count",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="blocking_count",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="blockers_count",
        ),
        migrations.RemoveField(
            model_name="profileevent",
            name="blocking_count",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."created", NEW."id", NEW."image", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="2f942d85704811ae9eda8402084fe42635ded1c1",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_87e8d",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (NEW."banner_image", NEW."biography", NEW."created", NEW."id", NEW."image", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."target_content_type_id", NEW."target_object_id"); RETURN NULL;',
                    hash="fae17467163367f41f0d95fe65fbd6394321be48",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c0aea",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profiles_profileevent" ("banner_image", "biography", "created", "id", "image", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "target_content_type_id", "target_object_id") VALUES (OLD."banner_image", OLD."biography", OLD."created", OLD."id", OLD."image", OLD."modified", OLD."name", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."target_content_type_id", OLD."target_object_id"); RETURN NULL;',
                    hash="e06b87143e6be16a146b74bb0a9dff918566f184",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_4fa3e",
                    table="profiles_profile",
                    when="AFTER",
                ),
            ),
        ),
    ]
