# Generated by Django 5.0.9 on 2024-10-23 14:20

import baseapp_wagtail.models
import baseapp_wagtail.base.stream_fields.page_body_stream_field
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "featured_image",
                    wagtail.fields.StreamField(
                        [("featured_image", 2)],
                        block_lookup={
                            0: (
                                "baseapp_wagtail.blocks.basic_blocks.custom_image_chooser_block.block.CustomImageChooserBlock",
                                (),
                                {"image_sizes": None, "required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": 'If this is a <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">decorative image</a>, please leave this field blank.',
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 0), ("alt_text", 1)]],
                                {},
                            ),
                        },
                        null=True,
                        verbose_name="Featured Image",
                    ),
                ),
                (
                    "body",
                    baseapp_wagtail.base.stream_fields.page_body_stream_field.PageBodyStreamField(
                        [("section_stream_block", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "baseapp_wagtail.blocks.basic_blocks.custom_rich_text_block.block.CustomRichTextBlock",
                                (),
                                {"icon": "pilcrow"},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 50, "required": True, "use_json_field": True},
                            ),
                            2: (
                                "baseapp_wagtail.blocks.basic_blocks.custom_rich_text_block.block.CustomRichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ul", "hr"],
                                    "icon": "pilcrow",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {"admin_text": "<hr />", "label": " "},
                            ),
                            4: (
                                "baseapp_wagtail.blocks.basic_blocks.custom_image_chooser_block.block.CustomImageChooserBlock",
                                (),
                                {"label": " ", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "blank": True,
                                    "choices": [("left", "Left"), ("right", "Right")],
                                    "help_text": "This indicates the position of the image in the desktop view.",
                                    "label": "Image Position",
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 1),
                                        ("description", 2),
                                        ("hr", 3),
                                        ("featured_image", 4),
                                        ("image_position", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.StreamBlock",
                                [[("rich_text_block", 0), ("banner_block", 6)]],
                                {"required": False},
                            ),
                        },
                        verbose_name="Page body",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard page",
                "verbose_name_plural": "Standard pages",
                "abstract": False,
            },
            bases=(baseapp_wagtail.models.HeadlessPageMixin, "wagtailcore.page"),
        ),
    ]
