# Generated by Django 5.2.14 on 2026-05-21 12:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import baseapp_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=baseapp_core.models.random_name_in("chat_room_images"),
                        verbose_name="image",
                    ),
                ),
                (
                    "last_message_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ("participants_count", models.IntegerField(default=0)),
                ("messages_count", models.IntegerField(default=0)),
                ("is_group", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_created_rooms",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_time", "-created"],
                "abstract": False,
                "swappable": "BASEAPP_CHATS_CHATROOM_MODEL",
            },
        ),
        migrations.CreateModel(
            name="ChatRoomParticipant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("role", models.IntegerField(choices=[(1, "member"), (2, "admin")], default=1)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("has_archived_room", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to=settings.BASEAPP_CHATS_CHATROOM_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-role", "profile__name"],
                "abstract": False,
                "swappable": "BASEAPP_CHATS_CHATROOMPARTICIPANT_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "message_type",
                    models.IntegerField(
                        choices=[(1, "User message"), (2, "System message")], default=1
                    ),
                ),
                (
                    "verb",
                    models.IntegerField(
                        choices=[(100, "sent a message")], db_index=True, default=100
                    ),
                ),
                (
                    "action_object_object_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("extra_data", models.JSONField(blank=True, null=True)),
                (
                    "action_object_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_object",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "content_linked_profile_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_as_content_actor_set",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
                (
                    "content_linked_profile_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_as_content_target_set",
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
                (
                    "in_reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to=settings.BASEAPP_CHATS_MESSAGE_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.BASEAPP_CHATS_CHATROOM_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
                "swappable": "BASEAPP_CHATS_MESSAGE_MODEL",
            },
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.BASEAPP_CHATS_MESSAGE_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MessageStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to=settings.BASEAPP_CHATS_MESSAGE_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BASEAPP_CHATS_MESSAGESTATUS_MODEL",
            },
        ),
        migrations.CreateModel(
            name="UnreadMessageCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("marked_unread", models.BooleanField(default=False)),
                ("count", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.BASEAPP_PROFILES_PROFILE_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unread_messages",
                        to=settings.BASEAPP_CHATS_CHATROOM_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
                "swappable": "BASEAPP_CHATS_UNREADMESSAGECOUNT_MODEL",
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroomparticipant",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'social_chats' AND model = 'chatroomparticipant'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="6b963cd80750ff5c6f0d097040d558c64833b82d",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_3d01b",
                    table="social_chats_chatroomparticipant",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroomparticipant",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'social_chats' AND model = 'chatroomparticipant')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="fa983dfd0f8d37b6fcc2e39115103c8241956792",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_44522",
                    table="social_chats_chatroomparticipant",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'social_chats' AND model = 'message'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="41d86a80c2446db3e7f941c7f113155658fdc8d4",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_f9541",
                    table="social_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'social_chats' AND model = 'message')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="8cad4e662b6ab5f012f4ae1a44fce6c2abc93511",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_ee8f1",
                    table="social_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="set_last_message",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            UPDATE social_chats_chatroom\n            SET last_message_id = NEW.id, last_message_time = NEW.created\n            WHERE id = NEW.room_id;\n            RETURN NULL;\n        ",
                    hash="606dcba6b08050e3934db2b54b8770ceca8c613c",
                    operation="INSERT",
                    pgid="pgtrigger_set_last_message_99301",
                    table="social_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="create_message_status",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."message_type" = 1)',
                    func="\n            INSERT INTO social_chats_messagestatus (message_id, profile_id, is_read)\n            SELECT NEW.id, crp.profile_id, CASE WHEN NEW.profile_id = crp.profile_id THEN TRUE ELSE FALSE END\n            FROM social_chats_chatroomparticipant as crp\n            WHERE crp.room_id = NEW.room_id;\n            RETURN NULL;\n        ",
                    hash="7e6fbfefcf587ec80c52efd6e6922e27f507644e",
                    operation="INSERT",
                    pgid="pgtrigger_create_message_status_46f63",
                    table="social_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="update_last_message",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            UPDATE social_chats_chatroom\n            SET last_message_id = (\n                SELECT id\n                FROM social_chats_message\n                WHERE room_id = OLD.room_id\n                ORDER BY created DESC\n                LIMIT 1\n            ),\n            last_message_time = (\n                SELECT created\n                FROM social_chats_message\n                WHERE room_id = OLD.room_id\n                ORDER BY created DESC\n                LIMIT 1\n            )\n            WHERE id = OLD.room_id;\n            RETURN NULL;\n        ",
                    hash="3da1a92052896d04f8ff261da7c4532a2f206425",
                    operation="DELETE",
                    pgid="pgtrigger_update_last_message_80435",
                    table="social_chats_message",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroom",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'social_chats' AND model = 'chatroom'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="b2aea0a8de1556fa4444ada8bce30c97816a81a9",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_23913",
                    table="social_chats_chatroom",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="chatroom",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'social_chats' AND model = 'chatroom')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="87664970bfb2ddd00bf9d9e8379d01140b1d1c35",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_3b7f9",
                    table="social_chats_chatroom",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagestatus",
            unique_together={("message_id", "profile_id")},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'social_chats' AND model = 'messagestatus'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="66de5fbc3da2bc75fc93328f547bf913d4eb96d4",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_f9eb5",
                    table="social_chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'social_chats' AND model = 'messagestatus')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="5619d62c95c0ba60131e47dfc395d07b095093fc",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_89cbc",
                    table="social_chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="increment_unread_count",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NOT NEW."is_read")',
                    func="\n            INSERT INTO social_chats_unreadmessagecount (room_id, profile_id, marked_unread, count)\n            VALUES ((SELECT room_id FROM social_chats_message WHERE id = NEW.message_id), NEW.profile_id, False, 1)\n            ON CONFLICT (room_id, profile_id)\n            DO UPDATE SET count = social_chats_unreadmessagecount.count + 1;\n            RETURN NULL;\n        ",
                    hash="1230cac3ab75901587de6d77e237f17edb030a8d",
                    operation="INSERT",
                    pgid="pgtrigger_increment_unread_count_44471",
                    table="social_chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messagestatus",
            trigger=pgtrigger.compiler.Trigger(
                name="decrement_unread_count",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."is_read" AND NOT OLD."is_read")',
                    func="\n            UPDATE social_chats_unreadmessagecount\n            SET count = GREATEST(0, count - 1)\n            WHERE\n                room_id = (SELECT room_id FROM social_chats_message WHERE id = NEW.message_id) AND\n                profile_id = NEW.profile_id;\n            RETURN NULL;\n        ",
                    hash="dd3233cf27ce3017e46500c3be1d079f0d32e76c",
                    operation="UPDATE",
                    pgid="pgtrigger_decrement_unread_count_bc803",
                    table="social_chats_messagestatus",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unreadmessagecount",
            unique_together={("room_id", "profile_id")},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="unreadmessagecount",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'social_chats' AND model = 'unreadmessagecount'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="58ae30435404d849f74a58d2331d0aa2b01778d5",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_fb7a5",
                    table="social_chats_unreadmessagecount",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="unreadmessagecount",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'social_chats' AND model = 'unreadmessagecount')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="066d365f2a1a2c7243a85359c3fca9ec184d3d0e",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_2d77e",
                    table="social_chats_unreadmessagecount",
                    when="AFTER",
                ),
            ),
        ),
    ]
