# Generated by Django 5.2.12 on 2026-03-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_api_key", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The datetime the API Key expires.",
                null=True,
                verbose_name="Expiry Date",
            ),
        ),
    ]
