# Generated by Django 5.0.6 on 2024-06-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0009_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Spanish"), ("pt", "Portuguese")],
                default="en",
                max_length=9,
            ),
        ),
    ]
