# Generated by Django 5.0.9 on 2024-11-27 01:22

import baseapp_core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_content_feed", "0001_initial"),
        migrations.swappable_dependency(settings.BASEAPP_CONTENT_FEED_CONTENTPOST_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=baseapp_core.models.random_name_in("profile_images"),
                        verbose_name="image",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_post",
                        to=settings.BASEAPP_CONTENT_FEED_CONTENTPOST_MODEL,
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BASEAPP_CONTENT_FEED_CONTENTPOSTIMAGE_MODEL",
            },
        ),
    ]
