# Generated by Django 4.2.11 on 2024-04-16 11:58

from django.apps import apps
from django.db import migrations, models


def _default_comments_count():
    return {
        "total": 0,
        "main": 0,
        "replies": 0,
        "pinned": 0,
        "reported": 0,
    }


if apps.is_installed("baseapp_comments"):
    from baseapp_comments.models import default_comments_count
else:
    default_comments_count = _default_comments_count


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_pages", "0003_remove_page_snapshot_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="comments_count",
            field=models.JSONField(
                default=default_comments_count,
                editable=False,
                verbose_name="comments count",
            ),
        ),
        migrations.AlterField(
            model_name="pageevent",
            name="comments_count",
            field=models.JSONField(
                default=default_comments_count,
                editable=False,
                verbose_name="comments count",
            ),
        ),
    ]
