# Generated by Django 5.1.15 on 2025-12-24 14:22

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_pages", "0008_remove_pageevent_pgh_context_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="metadata",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_pages' AND model = 'metadata'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="79c05306bf7af341459083ba3b37914337f11355",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_3d816",
                    table="baseapp_pages_metadata",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="metadata",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_pages' AND model = 'metadata')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="52e83cd0280428df0b87290af2cfbb9f714aedb0",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_3bfe1",
                    table="baseapp_pages_metadata",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="urlpath",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_pages' AND model = 'urlpath'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="06f28409327600daa00f5a03052ff36010e11bf8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_cf506",
                    table="baseapp_pages_urlpath",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="urlpath",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_pages' AND model = 'urlpath')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="aef74f65a12ffae2cb409dfad1c85a5c3036a9f0",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_fbee1",
                    table="baseapp_pages_urlpath",
                    when="AFTER",
                ),
            ),
        ),
    ]
