# Generated by Django 5.1.11 on 2025-09-02 23:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_pages", "0008_remove_pageevent_pgh_context_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_pages' AND model = 'page')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="58debed89bbfda706dcec68a10b6d3c90c1819ed",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_cd863",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
    ]
