# Generated by Django 5.1.11 on 2025-09-11 18:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_pages", "0009_page_delete_public_id_mapping"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="metadata",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_pages' AND model = 'metadata')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="f813aa9425455b8f5b6baa933f8e8093d1d93d3e",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_6513f",
                    table="baseapp_pages_metadata",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="urlpath",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_pages' AND model = 'urlpath')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="b76b627577c8609917f879ef47ceb1e50e926092",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_cb240",
                    table="baseapp_pages_urlpath",
                    when="AFTER",
                ),
            ),
        ),
    ]
