# Generated by Django 5.2.12 on 2026-03-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_pages", "0009_metadata_insert_document_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Page",
        ),
    ]
