# Generated by Django 5.2.3 on 2025-11-12 16:03

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_pages", "0009_metadata_insert_public_id_mapping_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="insert_public_id_mapping",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="delete_public_id_mapping",
        ),
    ]
