# Generated by Django 5.1.11 on 2025-11-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_pages", "0009_metadata_insert_document_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="page",
            name="is_comments_enabled",
        ),
    ]
