# Generated by Django 4.2.9 on 2024-01-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="following_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
