# Generated by Django 4.2.11 on 2024-03-28 02:31

from django.db import migrations, models

import baseapp_comments.models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_comments", "0002_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comments_count",
            field=models.JSONField(
                default=baseapp_comments.models.default_comments_count,
                editable=False,
                verbose_name="comments count",
            ),
        ),
    ]
