# Generated by Django 5.0.6 on 2025-03-27 09:12

from django.db import migrations, models

import baseapp_comments.models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_comments", "0016_remove_commentevent_in_reply_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comments_count",
                    models.JSONField(
                        default=baseapp_comments.models.default_comments_count,
                        editable=False,
                        verbose_name="comments count",
                    ),
                ),
                (
                    "is_comments_enabled",
                    models.BooleanField(default=True, verbose_name="is comments enabled"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
