# Generated by Django 3.2.19 on 2023-05-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cache", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialauthaccesstokencache",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
