# Generated by Django 5.2.14 on 2026-06-24 18:39

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("social_mentions", "0001_initial"),
        migrations.swappable_dependency(settings.BASEAPP_PROFILES_PROFILE_MODEL),
    ]

    operations = [
        # `AbstractBaseMention` now inherits `target_document` from
        # `DocumentIdTargetMixin` instead of declaring `target` by hand. Rename
        # the existing column (target_id -> target_document_id) to preserve data;
        # the rename auto-updates the unique_together reference.
        migrations.RenameField(
            model_name="mention",
            old_name="target",
            new_name="target_document",
        ),
        # Align the renamed field's attributes with the mixin (related_name +
        # verbose_name change only — no database effect).
        migrations.AlterField(
            model_name="mention",
            name="target_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="mention",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'social_mentions' AND model = 'mention'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="d79c95bde62c9afb7077f1b01df9138d4f9cdae1",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_cde1f",
                    table="social_mentions_mention",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="mention",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'social_mentions' AND model = 'mention')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="35c189e4ee80eae564343c70aab31719e0c82f37",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_9811f",
                    table="social_mentions_mention",
                    when="AFTER",
                ),
            ),
        ),
    ]
