# Generated by Django 5.0.11 on 2025-02-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_payments", "0002_create_template_emails"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Plan",
        ),
    ]
