# Generated by Django 5.1.13 on 2025-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_payments", "0005_customer_created_customer_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
