# Generated by Django 5.2.1 on 2025-07-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_payments", "0005_customer_created_customer_modified_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together=set(),
        ),
    ]
