# Generated by Django 5.2.1 on 2025-06-26 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_payments", "0005_customer_created_customer_modified_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="authorized_users",
            field=models.ManyToManyField(
                blank=True, related_name="customer_access", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
