# Generated by Django 5.2.1 on 2025-07-14 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_payments", "0006_alter_customer_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subscription",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.BASEAPP_PAYMENTS_CUSTOMER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="remote_customer_id",
        ),
    ]
