# Generated by Django 5.2.3 on 2025-10-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_payments", "0006_alter_customer_id_alter_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
