# Generated by Django 5.2.14 on 2026-06-08 13:03

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models

import baseapp_ratings.migration_helpers.convert_rates_gfk_into_document_id_helper


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatableMetadata",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "target",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ratable_metadata",
                        serialize=False,
                        to="baseapp_core.documentid",
                    ),
                ),
                ("ratings_count", models.IntegerField(default=0, editable=False)),
                ("ratings_sum", models.IntegerField(default=0, editable=False)),
                ("ratings_average", models.FloatField(default=0, editable=False)),
                ("is_ratings_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ratable metadata",
                "verbose_name_plural": "ratable metadata",
                "abstract": False,
                "swappable": "BASEAPP_RATINGS_RATABLEMETADATA_MODEL",
            },
        ),
        migrations.AddField(
            model_name="rate",
            name="target_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings_inbox",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.RunPython(
            code=baseapp_ratings.migration_helpers.convert_rates_gfk_into_document_id_helper.migrate_rate_targets_to_document_id,
            reverse_code=baseapp_ratings.migration_helpers.convert_rates_gfk_into_document_id_helper.reverse_migrate_rate_targets_to_generic_fk,
        ),
        migrations.AlterField(
            model_name="rate",
            name="target_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings_inbox",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rate",
            unique_together=set(),
        ),
        migrations.RemoveIndex(
            model_name="rate",
            name="ratings_rat_target__367d45_idx",
        ),
        migrations.RemoveField(
            model_name="rate",
            name="target_content_type",
        ),
        migrations.RemoveField(
            model_name="rate",
            name="target_object_id",
        ),
        migrations.AlterUniqueTogether(
            name="rate",
            unique_together={("user", "target_document")},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="rate",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="rate",
            name="delete_document_id",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="rate",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'ratings' AND model = 'rate'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="78096f57a3e2bddaa627abc86c8d0b97b6288775",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_62388",
                    table="ratings_rate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="rate",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'ratings' AND model = 'rate')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="031c060f47aa422e4730994e599037e102311262",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_3b27f",
                    table="ratings_rate",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AlterField(
            model_name="ratablemetadata",
            name="target",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="baseapp_core.documentid",
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="target_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
    ]
