# Generated by Django 5.2.12 on 2026-05-07 16:40

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0003_convert_target_to_document"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="rate",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="rate",
            name="delete_document_id",
        ),
        migrations.RenameIndex(
            model_name="rate",
            new_name="ratings_rat_target__e6a884_idx",
            old_name="ratings_rat_target__d39bff_idx",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="rate",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'ratings' AND model = 'rate'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="78096f57a3e2bddaa627abc86c8d0b97b6288775",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_62388",
                    table="ratings_rate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="rate",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'ratings' AND model = 'rate')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="031c060f47aa422e4730994e599037e102311262",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_3b27f",
                    table="ratings_rate",
                    when="AFTER",
                ),
            ),
        ),
    ]
