# Generated by Django 5.2.14 on 2026-06-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("ratings", "0004_remove_rate_insert_document_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratablemetadata",
            name="target",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="baseapp_core.documentid",
            ),
        ),
    ]
