# Generated by Django 4.2.15 on 2024-09-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0007_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="following_count",
        ),
    ]
