# Generated by Django 4.2.15 on 2024-09-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0008_remove_user_followers_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Spanish"), ("pt", "Portuguese")],
                default="en",
                max_length=9,
            ),
        ),
    ]
