# Generated by Django 5.0.1 on 2025-01-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0009_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_ratings_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ratings_average",
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="ratings_count",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="ratings_sum",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
