# Generated by Django 5.0.1 on 2025-02-08 01:57

from django.db import migrations, models

import baseapp_cloudflare_stream_field.field


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0010_user_is_ratings_enabled_user_ratings_average_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "video",
                    baseapp_cloudflare_stream_field.field.CloudflareStreamField(
                        blank=True, null=True
                    ),
                ),
            ],
        ),
    ]
