# Generated by Django 5.0.1 on 2025-02-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0011_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
