# Generated by Django 5.0.1 on 2024-06-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_comments", "0011_rename_new_profile_to_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-is_pinned", "-created"],
                "permissions": [
                    ("pin_comment", "can pin comments"),
                    ("report_comment", "can report comments"),
                    ("view_all_comments", "can view all comments"),
                    ("add_comment_with_profile", "can add comments with profile"),
                ],
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
            },
        ),
    ]
