# Generated by Django 3.2.16 on 2023-01-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.CharField(max_length=255, unique=True)),
                (
                    "exclude_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="excluded_permission_roles",
                        to="auth.Permission",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(blank=True, related_name="roles", to="auth.Group"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, related_name="roles", to="auth.Permission"),
                ),
            ],
        ),
    ]
