# Generated by Django 3.2.16 on 2023-01-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_drf_view_action_permissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IpRestriction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                (
                    "is_whitelisted",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this IP will be whitelisted",
                    ),
                ),
                (
                    "unrestricted_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="List of roles that will be unrestricted for this IP",
                        related_name="ips",
                        to="baseapp_drf_view_action_permissions.Role",
                    ),
                ),
            ],
        ),
    ]
