# Generated by Django 5.1.15 on 2025-12-15 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_profiles", "0006_alter_profile_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuserrole",
            name="invitation_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the invitation expires",
                null=True,
                verbose_name="invitation expires at",
            ),
        ),
        migrations.AddField(
            model_name="profileuserrole",
            name="invitation_token",
            field=models.CharField(
                blank=True,
                help_text="Unique token for accepting invitation",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="invitation token",
            ),
        ),
        migrations.AddField(
            model_name="profileuserrole",
            name="invited_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the invitation was sent",
                null=True,
                verbose_name="invited at",
            ),
        ),
        migrations.AddField(
            model_name="profileuserrole",
            name="invited_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address invitation was sent to (for pending invitations)",
                max_length=254,
                null=True,
                verbose_name="invited email",
            ),
        ),
        migrations.AddField(
            model_name="profileuserrole",
            name="responded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user accepted or declined",
                null=True,
                verbose_name="responded at",
            ),
        ),
        migrations.AlterField(
            model_name="profileuserrole",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "active"),
                    (2, "pending"),
                    (3, "inactive"),
                    (4, "declined"),
                    (5, "expired"),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="profileuserrole",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
