# Generated by Django 5.2.12 on 2026-03-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_profiles", "0006_alter_profile_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="followers_count",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="following_count",
        ),
    ]
