# Generated by Django 5.1.11 on 2025-09-11 18:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_profiles", "0006_alter_profile_name"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="profileuserrole",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_profiles' AND model = 'profileuserrole')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="40b0681c02ae9531f1004fd247434d671a38d8c6",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_cd386",
                    table="baseapp_profiles_profileuserrole",
                    when="AFTER",
                ),
            ),
        ),
    ]
