# Generated by Django 5.1.14 on 2025-12-03 04:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_profiles", "0006_alter_profile_name"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="profileuserrole",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_profiles' AND model = 'profileuserrole'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="4e77628d5e8fa145da973e69227b8179586f819e",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_a07a7",
                    table="baseapp_profiles_profileuserrole",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profileuserrole",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_profiles' AND model = 'profileuserrole')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="faeb22b7db309a74c78ffd124838bdf69da7e196",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_c2be7",
                    table="baseapp_profiles_profileuserrole",
                    when="AFTER",
                ),
            ),
        ),
    ]
