# Generated by Django 5.1.15 on 2026-02-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_profiles", "0009_profileuserrole_unique_profile_invited_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuserrole",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "active"),
                    (2, "pending"),
                    (3, "inactive"),
                    (4, "declined"),
                    (5, "expired"),
                ],
                default=3,
            ),
        ),
    ]
