# Generated by Django 5.1.15 on 2026-02-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_profiles", "0010_add_invitation_delivery_tracking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileuserrole",
            name="invitation_last_send_provider_message_id",
        ),
        migrations.AlterField(
            model_name="profileuserrole",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "active"),
                    (2, "pending"),
                    (3, "inactive"),
                    (4, "declined"),
                    (5, "expired"),
                ],
                default=3,
            ),
        ),
    ]
