# Generated by Django 5.1.13 on 2025-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e2e", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
