# Generated by Django 5.1.14 on 2025-12-03 04:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_reactions", "0004_alter_reaction_unique_together_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="reaction",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_reactions' AND model = 'reaction'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="502b827f8e042694c6270cad7d449dbe2f49eb9f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_e4d04",
                    table="baseapp_reactions_reaction",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reaction",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_reactions' AND model = 'reaction')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="68dd1949483971c66dce6a86f7d62f960172f448",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_4aba5",
                    table="baseapp_reactions_reaction",
                    when="AFTER",
                ),
            ),
        ),
    ]
