# Generated by Django 5.1.11 on 2025-09-15 14:28

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_reactions", "0004_alter_reaction_unique_together_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="reaction",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_publicidmapping (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_reactions' AND model = 'reaction'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="4ddaca3ca6b3319718da7ac296a80a50b67c89e8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_public_id_mapping_3d793",
                    table="baseapp_reactions_reaction",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reaction",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_reactions' AND model = 'reaction')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="a937055a06fb8c63f9ba62a9a38df45ee0c0daa4",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_39b96",
                    table="baseapp_reactions_reaction",
                    when="AFTER",
                ),
            ),
        ),
    ]
