# Generated by Django 5.1.5 on 2025-01-27 20:45
import django.db.models.deletion
import swapper
from django.conf import settings
from django.db import migrations, models

import baseapp_core.models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_content_feed", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        swapper.dependency("baseapp_content_feed", "ContentPostImage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=baseapp_core.models.random_name_in("profile_images"),
                        verbose_name="image",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_post",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": swapper.swappable_setting("baseapp_content_feed", "ContentPostImage"),
            },
        ),
    ]
