# Generated by Django 5.1.7 on 2025-03-20 18:02

from django.db import migrations, models

import baseapp_core.models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_content_feed", "0002_contentpostimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpostimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=baseapp_core.models.random_name_in("content_feed_images"),
                verbose_name="image",
            ),
        ),
    ]
