# Generated by Django 5.1.15 on 2025-12-24 14:29

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import baseapp_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "content_types",
                    models.ManyToManyField(
                        blank=True, related_name="report_types", to="contenttypes.contenttype"
                    ),
                ),
                (
                    "parent_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_types",
                        to=settings.BASEAPP_REPORTS_REPORTTYPE_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "baseapp_reports_reporttype",
                "abstract": False,
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("report_subject", models.TextField(blank=True, null=True)),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.BASEAPP_REPORTS_REPORTTYPE_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "baseapp_reports_report",
                "abstract": False,
            },
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reporttype",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'reporttype'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="e35faf1a1ffa498f880c4261f7340a9c278dbab5",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_0b1de",
                    table="baseapp_reports_reporttype",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reporttype",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'reporttype')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="930ac3d29d1ecae0be8f63e33ab278f14dc92303",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_6c04a",
                    table="baseapp_reports_reporttype",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="baseapp_rep_target__171117_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("user", "target_content_type", "target_object_id")},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'report'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="0ebc93d438d00fb612ea6b19ea35246cf5d11af6",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_4154d",
                    table="baseapp_reports_report",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'report')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="693bfda67f3c33af8ba8f7d634b3936dbed6710d",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_9d810",
                    table="baseapp_reports_report",
                    when="AFTER",
                ),
            ),
        ),
    ]
