# Generated by Django 5.2.14 on 2026-06-08 13:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models

import baseapp_reports.migration_helpers.convert_reports_gfk_into_document_id_helper
import baseapp_reports.models
from baseapp_reports.migration_helpers.seed_default_report_types_helper import (
    reverse_seed_default_report_types,
    seed_default_report_types,
)

CONTENT_TYPE_TARGETS = {
    "comment": ("comments", "Comment"),
    "page": ("pages", "Page"),
    "profile": ("profiles", "Profile"),
}


def backwards(apps, schema_editor):
    reverse_seed_default_report_types(apps, schema_editor)


def forwards(apps, schema_editor):
    seed_default_report_types(
        apps,
        schema_editor,
        content_type_targets=CONTENT_TYPE_TARGETS,
    )


class Migration(migrations.Migration):

    replaces = [
        ("reports", "0002_reportablemetadata"),
        ("reports", "0003_seed_default_report_types"),
        ("reports", "0004_convert_target_to_document"),
        ("reports", "0005_remove_report_insert_document_id_and_more"),
        ("reports", "0006_alter_reportablemetadata_target"),
        ("reports", "0007_alter_report_target_document"),
    ]

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportableMetadata",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "target",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="reportable_metadata",
                        serialize=False,
                        to="baseapp_core.documentid",
                    ),
                ),
                (
                    "reports_count",
                    models.JSONField(
                        default=baseapp_reports.models.default_reports_count,
                        editable=False,
                        verbose_name="reports count",
                    ),
                ),
            ],
            options={
                "verbose_name": "reportable metadata",
                "verbose_name_plural": "reportable metadata",
                "abstract": False,
            },
        ),
        migrations.RunPython(
            code=forwards,
            reverse_code=backwards,
        ),
        migrations.AddField(
            model_name="report",
            name="target_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_inbox",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.RunPython(
            code=baseapp_reports.migration_helpers.convert_reports_gfk_into_document_id_helper.migrate_report_targets_to_document_id,
            reverse_code=baseapp_reports.migration_helpers.convert_reports_gfk_into_document_id_helper.reverse_migrate_report_targets_to_generic_fk,
        ),
        migrations.AlterField(
            model_name="report",
            name="target_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_inbox",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together=set(),
        ),
        migrations.RemoveIndex(
            model_name="report",
            name="baseapp_rep_target__171117_idx",
        ),
        migrations.RemoveField(
            model_name="report",
            name="target_content_type",
        ),
        migrations.RemoveField(
            model_name="report",
            name="target_object_id",
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("user", "target_document")},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="report",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="report",
            name="delete_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="reporttype",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="reporttype",
            name="delete_document_id",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'report'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="c1b31dca0c0e61d2e93b36e2aabb915e99fbfdfb",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_4154d",
                    table="reports_report",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'report')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="cd38d94275f8c34fa8a760498e90bb27db0e8038",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_9d810",
                    table="reports_report",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reporttype",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'reporttype'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="cd9f542f0f363887d67926ce6187af94624d301a",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_0b1de",
                    table="reports_reporttype",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reporttype",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'reporttype')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="0ad49ed8bc6f18ada06634e281afaab00484f943",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_6c04a",
                    table="reports_reporttype",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AlterField(
            model_name="reportablemetadata",
            name="target",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="baseapp_core.documentid",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="target_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="baseapp_core.documentid",
                verbose_name="target document",
            ),
        ),
    ]
