# Generated by Django 5.2.12 on 2026-05-07 16:40

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_convert_target_to_document"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="report",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="report",
            name="delete_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="reporttype",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="reporttype",
            name="delete_document_id",
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="reports_rep_target__e68343_idx",
            old_name="reports_rep_target__d39bff_idx",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'report'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="c1b31dca0c0e61d2e93b36e2aabb915e99fbfdfb",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_4154d",
                    table="reports_report",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'report')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="cd38d94275f8c34fa8a760498e90bb27db0e8038",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_9d810",
                    table="reports_report",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reporttype",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'reporttype'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="cd9f542f0f363887d67926ce6187af94624d301a",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_0b1de",
                    table="reports_reporttype",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reporttype",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'reports' AND model = 'reporttype')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="0ad49ed8bc6f18ada06634e281afaab00484f943",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_6c04a",
                    table="reports_reporttype",
                    when="AFTER",
                ),
            ),
        ),
    ]
