# Generated by Django 5.0.9 on 2024-11-21 17:17

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_message_templates", "0003_alter_emailtemplate_name_alter_smstemplate_name"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("target_object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("es", "Spanish"), ("pt", "Portuguese")],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Email subject line", max_length=255, null=True
                    ),
                ),
                (
                    "html_content",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Text that will be inputted into Template html version",
                        null=True,
                    ),
                ),
                (
                    "plain_text_content",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Text that will be inputted into Template plain text version",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_object_id", "language"],
                        name="baseapp_mes_target__bb4e37_idx",
                    )
                ],
                "unique_together": {("target_content_type", "target_object_id", "language")},
            },
        ),
    ]
