# Generated by Django 5.0.9 on 2024-11-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_message_templates", "0005_transfer_copies_to_translations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="html_content",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="plain_text_content",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="subject",
        ),
    ]
