# Generated by Django 5.0.1 on 2025-04-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_drf_view_action_permissions_tests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "permissions": [
                    ("view_testmodel_list", "Can List all testmodel"),
                    ("test_disable", "Can disable test"),
                    ("list_tests", "Can list tests"),
                    ("custom_action_testmodel", "Can custom action testmodel"),
                    ("custom_detail_action_testmodel", "Can custom detail action testmodel"),
                ],
            },
        ),
    ]
