# Generated by Django 5.1.15 on 2025-12-24 14:29

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models

import baseapp_core.hashids.models
import baseapp_core.models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyLegacyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DummyLegacyWithPkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            bases=(baseapp_core.hashids.models.LegacyWithPkMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DummyPublicIdModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            bases=(baseapp_core.models.DocumentIdMixin, models.Model),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="dummypublicidmodel",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'testapp' AND model = 'dummypublicidmodel'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="a61a79b04244a19bc587404884d1097dab2dc543",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_f8feb",
                    table="testapp_dummypublicidmodel",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="dummypublicidmodel",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'testapp' AND model = 'dummypublicidmodel')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="eb8d99ef7a6abac2340b307179d05c81c605ebab",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_f283a",
                    table="testapp_dummypublicidmodel",
                    when="AFTER",
                ),
            ),
        ),
    ]
