# Generated by Django 5.2.14 on 2026-06-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_core", "0001_initial"),
        ("testapp", "0002_dummylegacymodel_dummylegacywithpkmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyUniqueDocumentTarget",
            fields=[
                (
                    "target",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="baseapp_core.documentid",
                    ),
                ),
                ("counter", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DummyDocumentTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "target_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="baseapp_core.documentid",
                        verbose_name="target document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
