# Generated by Django 3.2.16 on 2023-01-10 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0004_auto_20160811_1614"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_changed_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="last date password was changed",
            ),
        ),
    ]
