# Generated by Django 5.1.15 on 2025-12-24 14:22

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseapp_notifications",
            "0003_rename_notification_recipient_unread_baseapp_not_recipie_8567c3_idx",
        ),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_notifications' AND model = 'notification'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="762bffc9d947f4c6c13861b0c2e6fee415b38e22",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_f840b",
                    table="baseapp_notifications_notification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_notifications' AND model = 'notification')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="c9b3344b44ed8d504d3282d7e9352c4ef46c4be9",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_eaecf",
                    table="baseapp_notifications_notification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notificationsetting",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'baseapp_notifications' AND model = 'notificationsetting'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="825660b602bd027518bccb8fa7c14678e40a2abb",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_5b65d",
                    table="baseapp_notifications_notificationsetting",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notificationsetting",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_notifications' AND model = 'notificationsetting')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="b7c53ad5a456f276224e6dd5d82775ae12f9ffef",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_70e43",
                    table="baseapp_notifications_notificationsetting",
                    when="AFTER",
                ),
            ),
        ),
    ]
