# Generated by Django 5.1.11 on 2025-09-11 18:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseapp_notifications",
            "0003_rename_notification_recipient_unread_baseapp_not_recipie_8567c3_idx",
        ),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_notifications' AND model = 'notification')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="ef1fa227e86ecb5fa10a65095361cb661be6afd1",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_c3d57",
                    table="baseapp_notifications_notification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notificationsetting",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'baseapp_notifications' AND model = 'notificationsetting')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="dc625d68f7248b05f52d8a5b132a944b7faa5572",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_3b735",
                    table="baseapp_notifications_notificationsetting",
                    when="AFTER",
                ),
            ),
        ),
    ]
