# Generated by Django 5.2.13 on 2026-04-17 18:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_notifications", "0004_notification_insert_document_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether the notification requires action from the recipient",
            ),
        ),
    ]
