# Generated by Django 5.2.12 on 2026-03-20 16:35

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_notifications", "0004_notification_insert_document_id_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="notification",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="notification",
            name="delete_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="notificationsetting",
            name="insert_document_id",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="notificationsetting",
            name="delete_document_id",
        ),
    ]
