# Generated by Django 5.2.13 on 2026-05-11 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_notifications", "0004_notification_insert_document_id_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="level",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                default="info",
                max_length=20,
                verbose_name="level",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["actor_content_type", "actor_object_id"],
                name="baseapp_not_actor_c_98171d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="baseapp_not_target__e55725_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["action_object_content_type", "action_object_object_id"],
                name="baseapp_not_action__c46c96_idx",
            ),
        ),
    ]
