# Generated by Django 3.2.19 on 2023-07-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
