# Generated by Django 5.1.11 on 2025-09-11 18:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_profile"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_public_id_mapping",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_publicidmapping\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'users' AND model = 'user')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="49a6e7d6dd4a50a8ef747799fa5d030da5d719d5",
                    operation="DELETE",
                    pgid="pgtrigger_delete_public_id_mapping_cd57d",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
