# Generated by Django 5.1.14 on 2025-12-03 04:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_profile"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            INSERT INTO baseapp_core_documentid (public_id, content_type_id, object_id, created, modified)\n            VALUES (\n                gen_random_uuid(),\n                (SELECT id FROM django_content_type WHERE app_label = 'users' AND model = 'user'),\n                NEW.id,\n                NOW(),\n                NOW()\n            )\n            ON CONFLICT (content_type_id, object_id) DO NOTHING;\n            RETURN NULL;\n            ",
                    hash="d236a8bf99e102e3d4e72626ce778b8c77fb8fd7",
                    operation="INSERT",
                    pgid="pgtrigger_insert_document_id_02f0d",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_document_id",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            DELETE FROM baseapp_core_documentid\n            WHERE\n                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'users' AND model = 'user')\n                AND object_id = OLD.id;\n            RETURN NULL;\n            ",
                    hash="4b6acd9ae5b1b088f74ef2a917f56bfe2d8dc559",
                    operation="DELETE",
                    pgid="pgtrigger_delete_document_id_ae92b",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
