# Generated by Django 5.1.15 on 2026-04-01 20:24

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_insert_document_id_user_delete_document_id"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="update_profile_name",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            IF NEW.profile_id IS NOT NULL THEN\n                UPDATE profiles_profile SET name = TRIM(NEW.first_name || ' ' || NEW.last_name) WHERE id = NEW.profile_id;\n            END IF;\n            RETURN NULL;\n        ",
                    hash="ce3775c2ba18cad79846f4095b690aa63c9fce84",
                    operation="UPDATE",
                    pgid="pgtrigger_update_profile_name_6a4ee",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="create_profile",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            IF NEW.profile_id IS NULL THEN\n                WITH new_profile AS (\n                    INSERT INTO profiles_profile (owner_id, target_content_type_id, target_object_id, name, status, created, modified)\n                    VALUES (\n                        NEW.id,\n                        (SELECT id FROM django_content_type WHERE app_label = 'users' AND model = 'user'),\n                        NEW.id,\n                        TRIM(NEW.first_name || ' ' || NEW.last_name),\n                        1,\n                        NOW(),\n                        NOW()\n                    )\n                    ON CONFLICT (target_content_type_id, target_object_id) DO UPDATE SET modified = EXCLUDED.modified\n                    RETURNING id\n                )\n                UPDATE users_user SET profile_id = (SELECT id FROM new_profile) WHERE id = NEW.id;\n            END IF;\n            RETURN NULL;\n        ",
                    hash="3610463e8a5e1942a07e2862cf4c9146fbf408c9",
                    operation="INSERT",
                    pgid="pgtrigger_create_profile_2293f",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
