# Generated by Django 5.1.15 on 2026-04-01 21:29

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_update_profile_name_user_create_profile"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="create_profile",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="create_profile",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n            IF NEW.profile_id IS NULL THEN\n                WITH new_profile AS (\n                    INSERT INTO profiles_profile (owner_id, target_content_type_id, target_object_id, name, status, created, modified, blockers_count, blocking_count, reports_count, comments_count, is_comments_enabled)\n                    VALUES (NEW.id, (SELECT id FROM django_content_type WHERE app_label = \'users\' AND model = \'user\'), NEW.id, TRIM(NEW.first_name || \' \' || NEW.last_name), 1, NOW(), NOW(), 0, 0, \'{"total":0}\'::jsonb, \'{"total":0,"main":0,"replies":0,"pinned":0,"reported":0}\'::jsonb, TRUE)\n                    ON CONFLICT (target_content_type_id, target_object_id) DO UPDATE SET modified = EXCLUDED.modified\n                    RETURNING id\n                )\n                UPDATE users_user SET profile_id = (SELECT id FROM new_profile) WHERE id = NEW.id;\n            END IF;\n            RETURN NULL;\n        ',
                    hash="10b72c5c517d416b60de10fdbdcd7b79d99654e5",
                    operation="INSERT",
                    pgid="pgtrigger_create_profile_2293f",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
