# Generated by Django 5.2.14 on 2026-06-08 13:57

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations

from baseapp_ratings.migration_helpers.convert_legacy_ratings_count_to_metadata_helper import (
    migrate_legacy_ratings_to_metadata,
    reverse_migrate_legacy_ratings_from_metadata,
)


def migrate_user_ratings(apps, schema_editor):
    migrate_legacy_ratings_to_metadata(
        apps,
        schema_editor,
        source_app_label="users",
        source_model_name="User",
        metadata_app_label="ratings",
    )


def reverse_migrate_user_ratings(apps, schema_editor):
    reverse_migrate_legacy_ratings_from_metadata(
        apps,
        schema_editor,
        source_app_label="users",
        source_model_name="User",
        metadata_app_label="ratings",
    )


class Migration(migrations.Migration):

    replaces = [
        ("users", "0006_drop_legacy_ratings_columns"),
        ("users", "0007_user_create_profile_drop_reports_count"),
        ("users", "0008_remove_user_create_profile_user_create_profile"),
    ]

    dependencies = [
        ("profiles", "0006_remove_reports_count"),
        ("ratings", "0002_ratablemetadata"),
        ("users", "0005_user_update_profile_name_user_create_profile"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_user_ratings,
            reverse_code=reverse_migrate_user_ratings,
        ),
        migrations.RemoveField(
            model_name="user",
            name="ratings_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ratings_sum",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ratings_average",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_ratings_enabled",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="create_profile",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="create_profile",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            IF NEW.profile_id IS NULL THEN\n                WITH new_profile AS (\n                    INSERT INTO profiles_profile (owner_id, target_content_type_id, target_object_id, name, created, modified, blockers_count, blocking_count, status)\n                    VALUES (NEW.id, (SELECT id FROM django_content_type WHERE app_label = 'users' AND model = 'user'), NEW.id, TRIM(COALESCE(NEW.first_name || ' ' || NEW.last_name, '')), NOW(), NOW(), 0, 0, 1)\n                    -- Conflicts arise when a Profile for this object already exists\n                    -- (e.g. seeded by a migration or a prior trigger run).  Refresh\n                    -- owner, name, and modified so the profile stays consistent with\n                    -- the current row rather than silently retaining stale values.\n                    ON CONFLICT (target_content_type_id, target_object_id) DO UPDATE\n                        SET owner_id = EXCLUDED.owner_id,\n                            name     = EXCLUDED.name,\n                            modified = EXCLUDED.modified\n                    RETURNING id\n                )\n                UPDATE users_user SET profile_id = (SELECT id FROM new_profile) WHERE id = NEW.id;\n            END IF;\n            RETURN NULL;\n        ",
                    hash="8b84a7d237a640ab50271b3ede907fc930fc9a3d",
                    operation="INSERT",
                    pgid="pgtrigger_create_profile_2293f",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="create_profile",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="create_profile",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            IF NEW.profile_id IS NULL THEN\n                WITH new_profile AS (\n                    INSERT INTO profiles_profile (owner_id, target_content_type_id, target_object_id, name, created, modified, status)\n                    VALUES (NEW.id, (SELECT id FROM django_content_type WHERE app_label = 'users' AND model = 'user'), NEW.id, TRIM(COALESCE(NEW.first_name || ' ' || NEW.last_name, '')), NOW(), NOW(), 1)\n                    -- Conflicts arise when a Profile for this object already exists\n                    -- (e.g. seeded by a migration or a prior trigger run).  Refresh\n                    -- owner, name, and modified so the profile stays consistent with\n                    -- the current row rather than silently retaining stale values.\n                    ON CONFLICT (target_content_type_id, target_object_id) DO UPDATE\n                        SET owner_id = EXCLUDED.owner_id,\n                            name     = EXCLUDED.name,\n                            modified = EXCLUDED.modified\n                    RETURNING id\n                )\n                UPDATE users_user SET profile_id = (SELECT id FROM new_profile) WHERE id = NEW.id;\n            END IF;\n            RETURN NULL;\n        ",
                    hash="d493a55f804860882bc44904f5e655167340be37",
                    operation="INSERT",
                    pgid="pgtrigger_create_profile_2293f",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
