# Generated by Django 5.2.14 on 2026-06-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_plugin_arch_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone name used to display dates and times for this user.",
                max_length=64,
                verbose_name="timezone",
            ),
        ),
    ]
