# Generated by Django 5.2.12 on 2026-04-06 20:48

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_create_profile_user_create_profile"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="update_profile_name",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="update_profile_name",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            IF NEW.profile_id IS NOT NULL THEN\n                UPDATE profiles_profile SET name = TRIM(NEW.first_name || ' ' || NEW.last_name) WHERE id = NEW.profile_id;\n            END IF;\n            RETURN NULL;\n        ",
                    hash="0b1159105390ad300841ee6a69fe009b91902f69",
                    operation='UPDATE OF "first_name", "last_name"',
                    pgid="pgtrigger_update_profile_name_6a4ee",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
