# Generated by Django 5.2.14 on 2026-06-18 01:25

from django.db import migrations, models

import baseapp_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone name used to display dates and times for this user.",
                max_length=64,
                validators=[baseapp_auth.models.validate_timezone],
                verbose_name="timezone",
            ),
        ),
    ]
