# Generated by Django 5.2.12 on 2026-04-21 18:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_create_profile_user_create_profile"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="update_profile_name",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="create_profile",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="update_profile_name",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            IF NEW.profile_id IS NOT NULL THEN\n                UPDATE profiles_profile SET name = TRIM(COALESCE(NEW.first_name || ' ' || NEW.last_name, '')) WHERE id = NEW.profile_id;\n            END IF;\n            RETURN NULL;\n        ",
                    hash="71767c2f4c21d09cc107d6f5da740d5d75072162",
                    operation='UPDATE OF "first_name", "last_name"',
                    pgid="pgtrigger_update_profile_name_6a4ee",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="create_profile",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            IF NEW.profile_id IS NULL THEN\n                WITH new_profile AS (\n                    INSERT INTO profiles_profile (owner_id, target_content_type_id, target_object_id, name, status, created, modified, blockers_count, blocking_count, reports_count, comments_count, is_comments_enabled)\n                    VALUES (NEW.id, (SELECT id FROM django_content_type WHERE app_label = 'users' AND model = 'user'), NEW.id, TRIM(COALESCE(NEW.first_name || ' ' || NEW.last_name, '')), 1, NOW(), NOW(), 0, 0, '{\"total\":0}'::jsonb, '{\"total\":0,\"main\":0,\"replies\":0,\"pinned\":0,\"reported\":0}'::jsonb, TRUE)\n                    -- Conflicts arise when a Profile for this object already exists\n                    -- (e.g. seeded by a migration or a prior trigger run).  Refresh\n                    -- owner, name, and modified so the profile stays consistent with\n                    -- the current row rather than silently retaining stale values.\n                    ON CONFLICT (target_content_type_id, target_object_id) DO UPDATE\n                        SET owner_id = EXCLUDED.owner_id,\n                            name     = EXCLUDED.name,\n                            modified = EXCLUDED.modified\n                    RETURNING id\n                )\n                UPDATE users_user SET profile_id = (SELECT id FROM new_profile) WHERE id = NEW.id;\n            END IF;\n            RETURN NULL;\n        ",
                    hash="12c309d7bcf2d0a86bff06d87d9f88f7bcfc2368",
                    operation="INSERT",
                    pgid="pgtrigger_create_profile_2293f",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
