name: Sonar Actions
run-name: ${{ github.actor }} is checking ${{ github.ref }} branch 🚀
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  baseapp-auth:
    uses: ./.github/workflows/sonar-workflow.yml
    with:
      project: baseapp-auth
    secrets: inherit
  baseapp-social-auth:
    uses: ./.github/workflows/sonar-workflow.yml
    with:
      project: baseapp-social-auth
    secrets: inherit
  baseapp-profiles:
    uses: ./.github/workflows/sonar-workflow.yml
    with:
      project: baseapp-profiles
    secrets: inherit
