# Generated by Django 5.2.14 on 2026-09-28 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payments", "0002_subscription_customer_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="entity_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="contenttypes.contenttype",
            ),
        ),
    ]
