# Generated by Django 5.2.14 on 2026-09-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payments", "0003_alter_customer_entity_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("entity_type", "entity_id")},
        ),
    ]
