# Generated by Django 5.2.14 on 2026-09-29 13:59

from django.db import migrations, models
from django.db.models import Count


def assert_no_duplicate_subscription_ids(apps, schema_editor) -> None:
    """Fail before the unique index is built, naming the rows that would break it.

    0001 only enforced uniqueness across (remote_customer_id, remote_subscription_id)
    and 0002 removed the first half, so two rows can legitimately share a Stripe
    subscription id by this point. Postgres would reject the index on its own, but with
    a message that names neither what the column means nor which ids are at fault.

    Deliberately not de-duplicated here: the duplicate rows differ by customer, so
    choosing a survivor means deciding whose subscription it is, and choosing wrong
    leaves the remaining row billing the wrong card. Only Stripe knows which is right.
    """
    Subscription = apps.get_model("payments", "Subscription")
    # Pinned to the database migrate is actually targeting. The default router would
    # answer from `default`, so with `migrate --database` this could clear a target that
    # does have duplicates, or block one that does not.
    database = schema_editor.connection.alias
    duplicated_ids = list(
        Subscription.objects.using(database)
        .values("remote_subscription_id")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
        .order_by("remote_subscription_id")
        .values_list("remote_subscription_id", flat=True)
    )
    if duplicated_ids:
        shown = ", ".join(duplicated_ids[:10])
        more = f" (and {len(duplicated_ids) - 10} more)" if len(duplicated_ids) > 10 else ""
        raise RuntimeError(
            "Cannot make Subscription.remote_subscription_id unique: "
            f"{len(duplicated_ids)} id(s) appear on more than one row - {shown}{more}. "
            "A Stripe subscription belongs to exactly one customer, so reconcile these "
            "against Stripe and remove the rows that do not match before migrating."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_customer_unique_together"),
    ]

    operations = [
        migrations.RunPython(assert_no_duplicate_subscription_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="subscription",
            name="remote_subscription_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
