# Generated by Django 5.2.14 on 2026-09-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_customer_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="remote_subscription_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
