# Generated by Django 5.0.8 on 2025-02-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StandardPage",
        ),
    ]
