# Generated by Django 5.1.11 on 2025-07-15 20:18

import wagtail.fields
from django.db import migrations

import baseapp_wagtail.base.stream_fields.featured_image_stream_field


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0003_alter_pagefortests_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagefortests",
            name="body",
            field=wagtail.fields.StreamField(
                [("custom_image_block", 2), ("custom_rich_text_block", 3), ("banner_block", 9)],
                blank=True,
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'If this is a <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">decorative image</a>, please leave this field blank.',
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("image", 0), ("alt_text", 1)]], {}),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True, "use_json_field": True},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ul", "hr"],
                            "icon": "pilcrow",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {"admin_text": "<hr />", "label": " "},
                    ),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": " ", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [("left", "Left"), ("right", "Right")],
                            "help_text": "This indicates the position of the image in the desktop view.",
                            "label": "Image Position",
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 4),
                                ("description", 5),
                                ("hr", 6),
                                ("featured_image", 7),
                                ("image_position", 8),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AlterField(
            model_name="pagefortests",
            name="featured_image",
            field=baseapp_wagtail.base.stream_fields.featured_image_stream_field.FeaturedImageStreamField(
                [("featured_image", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'If this is a <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">decorative image</a>, please leave this field blank.',
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("image", 0), ("alt_text", 1)]], {}),
                },
                null=True,
                verbose_name="Featured Image",
            ),
        ),
    ]
